apiVersion: v1
kind: PersistentVolume
metadata:
  name: video
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadOnlyMany
  storageClassName: openebs-hostpath
  hostPath:
    path: /home/jay/Video
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jaysdesktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Ti
  volumeName: video
