apiVersion: v1
kind: PersistentVolume
metadata:
  name: image
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/jay/Image
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jaysdesktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 100Gi
  volumeName: image
