apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: '<2.0.0'
  interval: 10m
  targetNamespace: cert-manager
  # See https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    crds:
      enabled: true
    prometheus:
      servicemonitor:
        enabled: true
