apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: '<2.0.0'
  interval: 10m
  targetNamespace: harbor
  # See https://github.com/goharbor/harbor-helm/blob/main/values.yaml
  values:
    expose:
      ingress:
        className: haproxy
        hosts:
          core: harbor.herron.dev
      tls:
        # Handled by host envoy proxy
        enabled: false
    externalURL: https://harbor.herron.dev
