apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: '<2.0.0'
  interval: 10m
  targetNamespace: harbor
  # See https://github.com/goharbor/harbor-helm/blob/main/values.yaml
  values:
    expose:
      ingress:
        className: haproxy
        annotations:
          cert-manager.io/cluster-issuer: acme
          external-dns.alpha.kubernetes.io/target: "97.117.2.112"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          haproxy.org/response-set-header: |
            Alt-Svc "h3=\":443\"; ma=86400"
            Cross-Origin-Resource-Policy "same-origin"
            Content-Security-Policy "frame-ancestors 'none'; upgrade-insecure-requests; report-to cf-nel"
            Referrer-Policy "same-origin"
            Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
            X-Content-Type-Options "nosniff"
          haproxy.org/ssl-redirect: "false"
        hosts:
          core: harbor.herron.dev
    externalURL: https://harbor.herron.dev
