apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 10m
  values:
    # See https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/installation/platforms/microk8s.md
    # Defaults: https://github.com/openebs/openebs/blob/develop/charts/values.yaml
    localprovisioner:
      basePath: /var/snap/microk8s/common/var/openebs/local
    ndm:
      sparse:
        path: /var/snap/microk8s/common/var/openebs/sparse
    varDirectoryPath:
      baseDir: /var/snap/microk8s/common/var/openebs
    loki:
      enabled: false
    alloy:
      enabled: false
