# Sourced from https://github.com/Elrondo46/davical-docker-standalone/blob/main/docker-compose.yml
# Set the following environment variables:
# - POSTGRES_PASSWORD: Should match PGSQL_ROOT_PASS
# - PGSQL_ROOT_PASS: Should match POSTGRES_PASSWORD
# - PASSDAVDB
# - ADMINDAVICALPASS

version: "3"

services:
  davical_db:
    container_name: davical_db
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pgsql_data:/var/lib/postgresql/data
  davical:
    container_name: davical
    image: tuxnvape/davical-standalone
    restart: unless-stopped
    env_file: .env
    environment:
      HOST_NAME: "jayherron.org"
      DBHOST: "davical_db"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      DAVICAL_LANG: "en_US"
    ports:
      - 8083:80
    volumes:
      - davical_config:/config
volumes:
  davical_config:
  pgsql_data:
