apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: timeseries-api
  namespace: timeseries-api
spec:
  selector:
    matchLabels:
      app: timeseries-api
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
