apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: timeseries-api
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  instances:
  - name: timeseries-api
    dataVolumeClaimSpec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
  instrumentation: {}
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
  postgresVersion: 16
  users:
    - name: timeseries-api
      databases:
        - timeseries-api
