# Encrypt this file with SOPS and save it as secret-backup.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: stackgres-backup-credentials
    namespace: timeseries-api
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:J40gDzv0mIR5cTLT+nhCgbY=,iv:0pyy1Q8fvURKJiOYDmNDkh2vrhj9WNOwSC1qKWrO+H0=,tag:KwKDyIbAmv4u1U6mpJEnWw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:HoFpYgqWyr6XS+T0Vk0mjWvDYECh/LyaV0dyYdtc,iv:e9cT7vqVVLwv3c7CfuMBqTPUoCybTk+sWZ5frqi4Kz0=,tag:gV58DT/MTBH3xXJ73jYLdg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:33:14Z"
    mac: ENC[AES256_GCM,data:xdeqfslvqFYhBd8JmYlSeYgzCm4sB0+CSVlfcsh+mM9o2HMfllOYe3QdJI2ngT/Olocve1guc9CmDKIPkbVv+jOECPimgvqBLPOpljKt84gGPPhsVOzdurGhN6s1qBHQgv1NQJskiICwzGtaDsEOciW2Km1wlW1MKkaFs48bxE8=,iv:25+ifS7zQ7QrMamBH7uGKDDScdI63mJysPgMGy0VS04=,tag:jDNPW+7Wzqz/MWNHswGN6Q==,type:str]
    pgp:
        - created_at: "2026-09-06T21:33:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqARAAi3JYrAn+BddMx4dEkPtdk+ZhMDwfRqAKxmI2G8PvcxMt
            OH90vP6aTwZ8db812z8UxoUTAnxWNjH4iVwCCOmmIJRXgHmKqRzazclNmsd+mBqO
            vqb+4UDhJGv8xT8m0snzIBLRqS0uBErV9i8jiIgTkNu6SQRn939ebhat5kyPnQ8o
            8NwKhEGVcNFcdDdtJ+OMqwnMTxQ/XTcpCyB6MhaHjlHESoqUWJjISQiiguEmdPmo
            pT7wy0EkJmEnL/dOaGmGFy0755d1osQd6w80B9PTj7ETTt75/9N3enKZSalZccjN
            aEf9Ff+7cqvZa/nsShx1RaWdUMbF3NVHSMN1bFphOrgSauY/UjasNyNU4xjwhisL
            xwgEQdJ8WFwVA11KniAr/OivTQumjOW441bHmN+IZnVPUztovtZSh3UztY6hsb/T
            CYKV+twZnD2T3aHl1poF8XutIVR5ce+dyssXaWqHLKMhPurfZ01je9/wRY6ZYBWu
            /733iy7ssG9hzvhUob485j3BTWcY6kwpeJu0MHhJAo+eoFnGy0iF84FHk3g2FdTz
            gySDJf5Z1xFcOdjcKFpgsAMnVe2aJ79d4d76kv0hga6UvGXG4qMYQ44DVWbjJokX
            cOxTaiRM12GdjEs0uY32/2DmvCl6lcgn4Bqnd6IuAGV6OLfUwtv8v8rqLFbjHYvU
            ZgEJAhBu1jDfyOo3hASJegC4jAdcGu70s07HPZjsSW1r3UbgDZD8lVSzL7/n1Odt
            zcGpsoJ4m91RRLPoYbpNlEC9LxFvHXCtnLWkzvgzuYmJPJsjLTI7aIenC/kfOezB
            WmrZqoDHrA==
            =YGgY
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
