apiVersion: stackgres.io/v1beta1
kind: SGObjectStorage
metadata:
  name: seaweedfs-backups
  namespace: timeseries-api
spec:
  type: s3Compatible
  s3Compatible:
    bucket: postgres-backups
    endpoint: http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
    region: us-east-1
    enablePathStyleAddressing: true
    awsCredentials:
      secretKeySelectors:
        accessKeyId:
          name: stackgres-backup-credentials
          key: accessKeyId
        secretAccessKey:
          name: stackgres-backup-credentials
          key: secretAccessKey
