# Encrypt this file with SOPS and save it as secret-backup.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: stackgres-backup-credentials
    namespace: health-db
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:JNi+b0D2MIr7k4qVwOhdrZU=,iv:fKD/3ZUg79nVZ5GVioL3IcoiMpE9sncfsZEuNq7q9EQ=,tag:Ma5lw7G0KWOxPnRLKDyPWQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:SEoSYCbAnyj2yphbbBziQOwqFcwqZLl3YqUbIUEd,iv:hb3g/B3XfDVihNgRs18ejXv1cdEb93vLGNq20fxya3k=,tag:XKPTq9U5WafX6qjzo0gRCg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:33:22Z"
    mac: ENC[AES256_GCM,data:T023DPdCpcK5OyarFuSQlR4eOwHO0KQZYMoPP9O9nt8oE0KVhmD6UKyCB/RuAqYXo8KVAAgPpaVoKr5XVxBYoPzAJipwHdWzkzHJgrdDO1MVOhhmXwy6aLTGDdM0glpWZoC9GJVq9nsOe5gb7k1v299l1mEbaOkhzCvsBLVlyLo=,iv:6RubpYbrZz6hYqqnj0ZqoLbm+X6Bb3gIeU8LW5nG0ss=,tag:baa9f82b0J6oIBoYornlOQ==,type:str]
    pgp:
        - created_at: "2026-09-06T21:33:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/+OTkiarjjf6Ue+M4NBdLoP1Id07lnU+/Mx7cj2xpkV/QQ
            9r+tn+jUWHTNOT+OWonixkrGeFCI4Ejwp8DZiUKfMjxZynaH879HsqCgdW6FuRJB
            YIg/8XrCfM5kEey5L6TuOSF0BMWmBXt80Jy7rFi1urkCLqG/2GImrSSSD3X//Ae+
            3e4k4DBHh0hvylHFWAodtROQS4h6/VqnrMAtEs/8irSPaKuT9uYtzEfSDaZpYlG8
            d/29DBkrj9cZK332At86dRyfHafHEI3OqXMEwbVpTgEWOuCbR+q07yL6Q71gUQO2
            AGn6jM/gLuz1fsjuDI+9pLcugBT5fUpW0WCkaQD9dUkmt8j9OAdpe+NKc4DljGpX
            O2ovMOZjROd86Wr2cy5DAoxMqOybpqsVMGS+59+4zjHo9EIlOYHqBkYnzM5WfUYV
            xvOSAJ0bpVLsOHmQI90kRjsvo/3bmJ2CsoDDjujcxaV5a3fmK80Yvn45mOGyVSJ+
            UPMifwkv9GbuC7ulcFHzcwZfgYuHRTm6pTS/qufH8cObe+qDDuA0SI8z9l/59KRE
            wU5L+Uiftv9JzvMIqmnUKdD4ln3zZ3RNjWFvS2ljJc2QiD9L8xkFc7Rsm9ipdpH+
            WHhHipj3C5UZqX/hubnm2WQc8/PexYK9Dmq/JG4bsrzkoWzPiMpo+oqMgm0cD1HU
            aAEJAhBaw/OZaZH2y31sirEmp+6sOCPQULzYXVV22Rq0ptLurVJQSqymFeKcbnpO
            R1F3uPTp+fD3B3HaY3+g+wldvUwOuTv8NdVtG8wizWVQCwWiy3qntM1aQP5TkFLJ
            PbNjoKayS8+Z
            =UGC1
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
