# https://hub.docker.com/_/nginx/
version: '3'
services:
  router:
    image: nginx
    container_name: router
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # You must provide your own certificate files
      - /etc/letsencrypt/live:/etc/nginx/certs:ro
