apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: public-ip-updater
  namespace: haproxy
  labels:
    app: public-ip-updater
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kubernetes-ingress"]
    verbs: ["get", "patch"]
