version: '3'
services:
  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    env_file: .env
    environment:
      - DOMAIN=https://bitwarden.jayherron.org
      - PUSH_ENABLED=true
      - SIGNUPS_ALLOWED=false
    ports:
      - 3010:80
    restart: unless-stopped
    volumes:
      - ~/Data/docker/bitwarden:/data/
