apiVersion: apps/v1
kind: Deployment
metadata:
  name: waterlog
  namespace: waterlog
  labels:
    app: waterlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterlog
  template:
    metadata:
      labels:
        app: waterlog
    spec:
      containers:
        - name: waterlog
          image: ghcr.io/needleinajaystack/waterlog:main
          ports:
            - name: waterlog
              containerPort: 8080
          environment:
            - name: DB_POSTGRES_HOST
              value: cluster
            - name: DB_POSTGRES_NAME
              value: waterlog
            - name: DB_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cluster
                  key: superuser-username
            - name: DB_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster
                  key: superuser-password
      imagePullSecrets:
        - name: ghcr
