apiVersion: apps/v1
kind: Deployment
metadata:
  name: waterlog
  namespace: waterlog
  labels:
    app: waterlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterlog
  template:
    metadata:
      labels:
        app: waterlog
    spec:
      containers:
        - name: waterlog
          image: ghcr.io/needleinajaystack/waterlog:main@sha256:d8af7fb7d846c982eea6086e53a7dee76b2dcff461d40f047931437898e902ec
          ports:
            - name: waterlog
              containerPort: 8080
          env:
            - name: WATERLOG_DB_POSTGRES_HOST
              value: cluster
            - name: WATERLOG_DB_POSTGRES_NAME
              value: waterlog
            - name: WATERLOG_DB_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cluster
                  key: superuser-username
            - name: WATERLOG_DB_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster
                  key: superuser-password
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 1Gi
      imagePullSecrets:
        - name: ghcr
