apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: waterlog
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:N9kExufdwqEchp2tI43umdCq3Fwz/qiq0ib8sNKimwBkiozFWmnUqeXez558/Thm3RPhcGy8mhAl0KA2NsrX9tKJoAWjVmw+8GbHeEV+QRuXUu/E9GgZXj3yQ/QcbGIjQmE9fHcQOSKSyK8FoapcvhnuPWXiU6ASGI2pn+/icyGIB/FSe8qOVN78/ZfYKE2LJTBeRv/EMf59NydAl01eLduVAhAwSjr9jK3xoSZQDdbDEQFRjnpd+7romZna753Ol6MU/Kg6GhuWK3fFBZMx+OBBJ1PhTM0irIB27q6SVs07OfRRu67U6vxZ2qxwiwFTHbmvQKlp/ofXfuQiGEWehYVnTctyHWo7+iIDIQ==,iv:a9DeCffr6kyN5IMQeqgpiSIu6bxp2rjJfnKQW2ushBI=,tag:8Hhg0DSFs3WeSFCNpzhmOw==,type:str]
sops:
    lastmodified: "2026-03-05T05:36:04Z"
    mac: ENC[AES256_GCM,data:r3zgqinR5v+e7SxkztfjR2DvfIQuFv5mXB7vAcNtP6l88QmxWqkBOUQ4DIPAm1fLvvvW5L3Ec47tawCo3s4gVbN7iGAd4UMYm9zletqOCZGZh47CwhUe8lg13pghH5gv9lbKO76ry/oUDTW737t5ATY4O6d3BM1MtmBvNNEVwxQ=,iv:/Ets+0uncoTSdtpecVwtYGhW/BUXOvvYk/lQJtkqI5U=,tag:Rj9M6D/nxPZGYkj8fHTYPQ==,type:str]
    pgp:
        - created_at: "2026-03-05T05:36:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//Ye8ebOzCuX2s1342+GTCuegGRWlHefbU+QJP3/vHB0wi
            lCbiEtz5K27109CisUO+1OrxwAAuMcNaEpGqikh95EF0d+a0UEQZZBB0mwRv5S+B
            CHILCtWmi84qf+RCah9VJFJ/RlvImxAxAkMmIjZgghSjMCc1qDAMDqGOoB+2i9Gr
            is2scPn5qUEPk4gvOrJsUAbxqLbKQl4HyKOoVIDfBzmY7VfVabQOZHff5OVI+y0k
            oY8e82PqTw6D8R7/UrZNFNwfkDRUqjM/MDd+laEPp8erFhSpc0iIhY/VmHpuMi9J
            NSUFlwd8zzpPCwfRVyUqwW+uS6q8mkkmOee7UNZnxJ56+wX6n64MpJQ/9ZYJ2H5u
            p3MVuYBtc2hTd2bLAsPTilTQuzlltIK/Ro00H0iNNgxQEfFFd60bhBbgK4vxSALu
            F1HorAmSjaacCNqgF59r9b17ftzWsc/byxL4mxHfmD7UsdxihvJGyxIKSxegA8qm
            QNSiwOsBFANbXqqfKwufXTq1enQ+GpeoCPTcrHj3t5TlLaToheVjlgWQsVlxlTlg
            wSJCJEG+T1k+LgcahB0cZoO1oxf1D8x2wj7C6GuMy7K1C9keKF8tvOlUYRIZjoYi
            GfTT9gJQL6O3F7Qz/HwjZvqtJGKr1aYYGh9m+qbtOjlFEaIk4Z9tw30zxzTbkXbU
            aAEJAhCi8AJZDnYSvWbBo3PmMJgRVE2Gd/o5yePnyjLnAVN46JYQSEyknmz/rf0S
            TnFF+Z8CePmz2drcSF7IT4K7YxYE+DcXynQb46N3ZkruZQ2xJwGC+n2gIzvHM+i3
            2TMybwQBa6iv
            =Y/vA
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
