# https://hay-kot.github.io/mealie/getting-started/install/
version: '3'
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie
    restart: unless-stopped
    environment:
      - DB_TYPE=sqlite
    ports:
      - 3001:80
    volumes:
      - ~/Data/docker/mealie:/app/data
    user: '1000'
