apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux
  namespace: flux-system
spec:
  selector:
    matchLabels: {} # Scrapes all pods in the namespace
  podMetricsEndpoints:
  - portNumber: 8080
