
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 10m
  targetNamespace: postgres-operator
  sourceRef:
    kind: GitRepository
    name: postgres-operator
  path: "./kustomize/install/default"
  prune: true
  wait: true
  timeout: 10m
