apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 10m
  # As recommended by CrunchyData, this is a fork of their examples: https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart#step-1-download-the-examples
  url: https://github.com/NeedleInAJayStack/postgres-operator
  ref:
    branch: main
