apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falco
      version: '<7.0.0'
  interval: 10m
  # See https://github.com/falcosecurity/charts/blob/master/charts/falco/values.yaml
  values:
    metrics:
      enabled: true
    serviceMonitor:
      create: true
