global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  
  # Unable to get this to work with host networking
  # - job_name: 'homeassistant'
  #   scheme: https
  #   static_configs:
  #     - targets: ['home.jayherron.org:443']
  #   metrics_path: /api/prometheus
  #   authorization:
  #     # CREATE MANUALLY: Long-Lived Access Token
  #     credentials_file: "/etc/prometheus/homeassistant-credentials.txt"

  # TODO: This doesn't work because envoy only serves to 127.0.0.1, not 172.17.0.1 (host.docker.internal)
  # - job_name: 'envoy'
  #   static_configs:
  #     - targets: ['host.docker.internal:9901']
  #   metrics_path: '/stats/prometheus'

# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: '<Your Grafana Username>'
#       password: '<Your Grafana API key>'