global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name: 'homeassistant'
    static_configs:
      - targets: ['homeassistant:8123']
    metrics_path: /api/prometheus
    authorization:
      # CREATE MANUALLY: Long-Lived Access Token
      credentials_file: "./homeassistant-credentials.txt"

# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: '<Your Grafana Username>'
#       password: '<Your Grafana API key>'