apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 10m
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
      version: "0.45.0"
  values:
    clusterRoleBinding:
      clusterRoleName: cluster-admin
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: headlamp
          paths:
            - path: /
              type: Prefix
      tls:
        - hosts:
            - headlamp
      annotations:
        tailscale.com/hostname: headlamp
