apiVersion: v1
kind: Secret
metadata:
    name: particle-sync
    namespace: particle-sync
data:
    apiUser: ENC[AES256_GCM,data:qnpiJA==,iv:02Xe/TqkfuLkamKjffPZkz+DSFZCOzCWkX+Ditvd+Ao=,tag:x5qxKgOAuleueMeQPh2HOg==,type:str]
    apiPassword: ENC[AES256_GCM,data:HHhFf+x2YVnukk5OcMpCDXHRzRb2WVLjKg+qqw==,iv:TmkhZaHghMOr3JvP7gnrXw39jCuhubpMFdaRkU6MmLc=,tag:lq/oBPWXax6Apyi0NCvO2Q==,type:str]
    particleUser: ENC[AES256_GCM,data:5nmwjZg4hdEm9pHSTj/782nlj8dAsDQauJcb9w9ygS86HJMAoaoQVOXfQV0=,iv:Om2Obn1mvrE6hd66m8+xqr5xBoaXyvTG2/TbTsn/lsw=,tag:JYzhsfltMffyt/utY9P7pw==,type:str]
    particlePassword: ENC[AES256_GCM,data:Wv6eYCgi1waHMzx4IOwcpLi+eCFpgTPDlzu89Q==,iv:r7F5bB1iyNUi6QaTyK+ih4uNEyWjcqYfqk5oYN1yewI=,tag:25ZV8DV3cR49QNFoWaal0Q==,type:str]
sops:
    lastmodified: "2025-09-12T04:08:04Z"
    mac: ENC[AES256_GCM,data:I5e35AUvJtFIXNqpS2RCdGh+RcxzAG5Tt8/1gaI8UDPttdsCWOkdw1eMxYDTwUsFAOXMpMZm++33dr7MlJBEUZJBAlzHDUdazcwjMT5KDWN5E6H71G6tmrE+BFv0gdUCCxVv6hkqpPz1SxOZ6hL3kdT8IXw2l+90wKtib3CyyZk=,iv:mv6yUfogwKzr01ji9jl+ri1DbtNmxECB1C58UzVLnco=,tag:sIp6lmkqFCh1edXTf4gO7w==,type:str]
    pgp:
        - created_at: "2025-09-12T04:08:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqARAAnw+CviS4bXwR+rN+amEJwcSAJE3Xn68XNuLp311qnOBw
            +nqeh3bmX4svzqqzLPQySxRcpk1TMOeikPsTUrkgB4LuU8lfaBPC8vGqSS4iL2X2
            M9cfGihCzAGd4wpymautNjaKpeysm5rI/y8S7NaDyuqde/P2Pahea+4EXHQV0gBF
            gXlnfHlh43j4JaCproMB8yDIKxQuiwK79SQPbVDaqBNHTiruq+JcvfdctI/hb8pp
            UK9F1y+WKY51SEmzSNjg7VXCJmRE0kWZG5bbJRnox5OrShPLPDGo6p6GuqErskde
            rQp+aABIeBdYuZndqdkcneVcRd4mCaKfGZC2ntmZyiUj3l7LgUyx7fnQvBnERVh0
            R2O7tIRGU2luFiXpYHkB3AkEIQeOxrTIyH5q+G+3SgwoSP1MyHxpaaEPG6Hfcgdl
            aGESq0Opb5qR+TRIU0Yr5zlgI7v6R1nfMX/lVXRP1AuwjRcYDhAUFZLs9mm3aux+
            4N4l73sXSIeDwPTy2TDnaSoB/5HSPMgHckoNn18gZxwIbzG03Qo2qr9CjDYFG7RN
            rmOip3c2HoO8lpbgGC6srny1218I9wnWXtGaY6/7zbE08/F97zhKZOX0ahlGDoEi
            kScpKfA7uvEPS0ZCTmtpXTVV5yzVIIAGvSIeEjeF48sWXqPa7t2QxnrXC12kN5nU
            aAEJAhD1QLQ2wTkvaqa6AsDOgDuwh1VIZXbh69fHxtVbkUDnDBTTuRpvu7L3yoqv
            jgGp/6f2Y5r3AqfTOk8kUzEFtJh4tavBl7EHOgbc9HTNjiN7qHx4vjgl+EkW0H5U
            XH9UeeYqaxax
            =JsoH
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
