apiVersion: v1
kind: Secret
metadata:
    name: particle-sync
    namespace: particle-sync
data:
    apiUser: ENC[AES256_GCM,data:bPohZQ==,iv:pvIjUbjFRTe4zG2edvbJBcAHjSjQi6FXwczWx4bv1Lo=,tag:xHlVlR1t9jlff5oOruO/UA==,type:str]
    apiPassword: ENC[AES256_GCM,data:hyetOeKSKHE5k45bTJJ2BvVZvZZy4sbymw80zg==,iv:IqnJiLZBuW61lv1ZTWvXrYWIvdAISlkccoXkw+rR+uc=,tag:1YCe9A3lvKyz69VF1xlOqg==,type:str]
    particleUser: ENC[AES256_GCM,data:1r5oEkVrcv8AgG4n3Tm9417UtFzo03C5AFdiRiolK3ysGf2BTbo7YLdyLLo=,iv:kVJTzenIYMZgMhp085AY5aEaP6mZH7Fe7wSpstb5V0Y=,tag:d5cp3vGzqoRgTW498cDHFQ==,type:str]
    particlePassword: ENC[AES256_GCM,data:5QKlp7kvDArAXBpG+WpkK50hT1xLU8XTrMhSoQ==,iv:VVcAdYwNd5nDFKYP1z4S2/UekP4Oam7xez1Sj3awaas=,tag:SciIR4GDdXoLM8DzsvYjhQ==,type:str]
sops:
    lastmodified: "2025-09-11T01:49:52Z"
    mac: ENC[AES256_GCM,data:bpwCjYYVghtxSE323157U+SN+OknPxVbuz3qiQHfwO2J355sd7FZaebSwhmXIUVxx07Uzpfekjq7Co97IGfuW08RzVsAMHtd3UAuPodsk4QQ+CT2IdKwHrwb2+xAeZEk2LwBwPzKIbqQUbqIa66THIQ++vYSWmAZ9yeSTqDsG6I=,iv:5QHQLBeDcCbKN3fTLNUDP3TbHOnPlzoTnQKeo2exHpg=,tag:1zF72TTq2hnrRrCztOMI3g==,type:str]
    pgp:
        - created_at: "2025-09-11T01:49:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//ZQeBOmuon2YQZ5LBVJ2Zgcd5fT4ziWEcJPqQuqswXHgv
            Spqi3UXSVhsoStJmpkOdUE1zNM2kv11V7sli2kILAe+22+lBcdBU1Onmgt9w9MAq
            e3ONrGfOFuenpY3WbxGi2Rwb4wLGSoeYugxeUq/8ZKqeB2fGGW8scarU+vzf9yye
            xGL9CCkQML2sk7uRET2Qs7FTzeFJi9OPDzeZ62PHjyPl8Q1rbA8kOINlO05bMH0j
            Wz82vjdf83VXIgZ0ch9C3j545SMswqG0NHeGWRq3YXETotJFSvbsIbTsO7lnpq+W
            HarWWCQ3jcUO/joN2EE0EXdZKHe7c3nh8K916j+gFlcRXGueMAsxR8JWEX7LiEEr
            uvY4HPjU7iXDgfNT7qk/Q90YO8qPGfKI/l/ShANL0KGUsLzNsTaohv8/pr6aD3sx
            8yGB5kkWN6LsmaW2f0pOvUnW2VPAmlvpxNjPQ9sVEs9ou0ipH9t5bfBabEzEYx/0
            gp+YSbe0XzL5Za8U8C2UZh97U2cmi3u0GvRdJdo/H+MLjdSOqa4Jh//F2JpxBOzo
            R4qVcO+O50hydZiUTvMyfBKw4+uFDMkVug/TQGkiYCr19+nEW7T3NZRznlnjvQW4
            vcReZ9SjbeYfbQOjudiTyYqiRaBFf85le0Pw03fO27Ebr00W1ZJFR+XE/ZUOHw/U
            aAEJAhBB2PIwNC7PlvRyVPjlt1DpgD8EmMpDptotq+BekPd8s+kYK3mAaEWnfsQg
            0WrvOUjRRIyLslTi5Zb9SaP0btCnYuYXJXcCzTCasBIna+sf0/Ihd/kwp2zwZGku
            q3cilh518G/s
            =c/yE
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
