apiVersion: apps/v1
kind: Deployment
metadata:
  name: herron-dot-dev
  namespace: herron-dot-dev
  labels:
    app: herron-dot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herron-dot-dev
  template:
    metadata:
      labels:
        app: herron-dot-dev
    spec:
      containers:
        - name: website
          image: ghcr.io/needleinajaystack/website@sha256:020f65d0e68e5ff1dbd34849fce04486b7f830c1e4068d8eb2652652a8e60f30
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
