# https://www.home-assistant.io/installation/linux#install-home-assistant-container
version: '3'
services:
  homeassitant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant
    restart: unless-stopped
    environment:
      - TZ=America/Denver
    network_mode: host
    privileged: true
    user: '1000'
    volumes:
      - ~/Data/docker/HomeAssistant:/config
