apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
