apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  serviceName: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:latest
          ports:
            - containerPort: 9000
          env:
            - name: BASE_URL
              value: https://recipes.herron.dev/
            - name: MAX_WORKERS
              value: '1'
            - name: TZ
              value: America/Denver
            - name: WEB_CONCURRENCY
              value: '1'
          volumeMounts:
            - name: mealie
              mountPath: /app/data
      volumes:
        - name: mealie
          persistentVolumeClaim:
            claimName: mealie
