apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: default
spec:
  interval: 24h
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: "./config/crd"
  prune: true
  timeout: 1m
