apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  chart:
    spec:
      chart: cni
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 10m
  targetNamespace: istio-system
  values:
    profile: ambient
