apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  chart:
    spec:
      chart: gateway
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 10m
  targetNamespace: istio-ingress
