apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: '<2.0.0'
  interval: 10m
  # See https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  # And https://kubernetes-sigs.github.io/external-dns/latest/docs/tutorials/cloudflare/#using-helm
  values:
    sources:
      - ingress
    serviceMonitor:
      enabled: true
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: cloudflare-api-token
