apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-collector
      version: '<7.0.0'
  interval: 10m
  # See https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml
  values:
    image:
      repository: otel/opentelemetry-collector-contrib
    mode: daemonset
    config:
      exporters:
        otlphttp:
          endpoint: http://loki.loki/otlp
      pipelines:
        logs:
          exporters:
            - otlphttp
        metrics:
          exporters: []
        traces:
          exporters: []
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: true
    ports:
      metrics:
        enabled: true
    podMonitor:
      enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
