apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-collector
      version: '<7.0.0'
  interval: 10m
  # See https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml
  values:
    image:
      repository: otel/opentelemetry-collector-contrib
    mode: daemonset
    config:
      exporters:
        otlphttp:
          endpoint: http://loki.loki:3100/otlp
      processors:
        batch:
          timeout: 1s
      service:
        pipelines:
          logs:
            exporters:
              - otlphttp
          metrics: null
          traces: null
    presets:
      logsCollection:
        # Disabled due to high open-telemetry CPU usage.
        enabled: true
    ports:
      metrics:
        enabled: true
    podMonitor:
      enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 4Gi
