apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: '<70.0.0'
  interval: 10m
  targetNamespace: kube-prometheus-stack
  values:
    replicaCount: 2