apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: kube-prometheus-stack
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      version: '<70.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 10m
  values:
    replicaCount: 2