apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale
  namespace: radicale
data:
  config: |-
    [auth]
    type = htpasswd
    htpasswd_filename = /etc/radicale/users
    htpasswd_encryption = plain

    [server]
    hosts = 0.0.0.0:5232, [::]:5232
