# Having a declared PVC increases the reuse and deletion safety over letting the StatefulSet manage it automatically.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: radicale
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
