apiVersion: v1
kind: Secret
metadata:
    name: radicale
    namespace: radicale
data:
    users: ENC[AES256_GCM,data:zMkFM9IAUdUPzvndPz8jgZUI+f3lrHFHkjsmmMaK8euUX0lf2heWToD7ohk1NJp+Rr/F5g==,iv:yk44ovB+gZKYxXf0UzNU2ZAIPTU01bJnvcAueMX2vHY=,tag:/94zwnoP7F1sQcbUIEOK/Q==,type:str]
sops:
    lastmodified: "2025-09-11T02:44:33Z"
    mac: ENC[AES256_GCM,data:y9OG9Et6Tr3C1bYLqtKk4Qy6oy/PhCoErzBtVdoAcOr7Km5AjzscOUaACtDMA6SmSJTJi7OCHOGTkXrdSM6FEADckvvElHOucqMOzAOBQQX99X9eNcY+7dhFLG4cMXkKCHZAfZDHLv1eebpvZwMV6xtRkBnqOD+SVoWaMQHgQl0=,iv:PrAcpfwqmIYLAlwNSFDwB+3z+EssReZw48/esmhgjgQ=,tag:JuUKD62tCmS/74Ht0AWXAQ==,type:str]
    pgp:
        - created_at: "2025-09-11T02:44:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/9FZLM7DdzjL2SFISvtWkbzWoF+NYwRvkVOS+D8DN7zwvF
            BAVMXKIHUCHEC/3Lz1cL/PlrQLEgqJyV1UqWZLX8oZ2J40dtw78CJz/yUNbeje57
            xXx9UIP8KXWctKrSFYJWAF3b9lbIYs96E7YnFaAezI/jbrnqN4YfdBfrOh07Gv36
            MUMDPny1Em7b8IDAHeCFAX7ga9DI9CQo3hqMUiMeXZ/3eMME/kYs4MHtkO33FBLx
            4JouDWwIdnK5b+o8Sy8CE3vz/pgbsAUcU3hJx/KyAhliomjIkszpxH/j24nJR1XV
            ZufkQI5zb6NFEO6tFDWfF/ETl8gmgXQprl6fvtx1vhN+Q4ra6btZjmKl3yXlzmdN
            DOuteiHI/JguQ6wBS4YwQMOxYllFcGKXqKHUZc8z7lM/KP9koKPc4F9pcyFRzo0s
            9VxDwfQpf1unxE0JDyI33/g9HeWs3Tj/3SyRc8PyE9ozISdG7UL2OPp3POsvspkP
            PLcrWYwdLNLvmZw4LEjgCYoenKdCfTE6dRyQqUZWE7fRkWEsaxTwYlXwAPXEVP+J
            VGbNHgxRru5HcQArcR75j2gmNPh3Pm/y/ax0uSQx0SjmlEv21JhUzRcL/ks+Nvw6
            MrzQaVcyk3Zhgv3f39D9gqX2pFPLk/sU7vuSdjnnV8vS9HGD0GVNftTkjSVkSunU
            ZgEJAhDeE0X0ZnJ9AfYwmBVGmIPqzvfp2mpptI9GEfCyO2gfzEwk2CQWqazsDW+L
            63tIUgyayttg/6jyPYM2wA+HX4pN3OMwwDgc2chSy3L2V7SETRKiDfNYMgsBnlZR
            nQk441eULQ==
            =Hsp0
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
