apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
data:
    client_id: ENC[AES256_GCM,data:5o2nOI6VCM4ja0kO6CAXtth7w1RqR+XH,iv:4OKTPb5wzzXUu7yrBRtuAkdQv6xlxXATFTIvgobnGLY=,tag:nuGz/7IydEDGvRNF+ZjZtw==,type:str]
    client_secret: ENC[AES256_GCM,data:WMa9OLAA0cg8IkoA5FlB6b3J6SumzHFYmWW1jpjeElUHCZGGUn3iX56L80jFs7734Dy8izylFYL5hSH25uGBkT7rlL5rcVooyBv/hImnS/iyjNVEdwuaHw==,iv:/7i/bXeXk/r2t4SRTZNaIt/ngfIXbOr7klOLXWk+MzA=,tag:ZzSlH2uBXQOa/JTnavmIPA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T23:47:23Z"
    mac: ENC[AES256_GCM,data:vhrw8Hl+YELtWI7HmfSDwb7ZshRuII5j+6F8cPe8FZdTI4XfV7FJ3aCHmqFj1cxA3bV/nnaFqx7TY6KNGPJknD5qC7dinGdwzi+aEqIAxfivBDlLeL9duq7nG5wRuuAy/hJrASTVBk1tzKvoULvM5fSHHaXSt5xgLjH5wHslE1M=,iv:dI5lIvhHgKnDgITjRiasINB9eJ1xRYwn+XBwZvPpN1w=,tag:3xu+2YZZy6wZayDyBvxBTA==,type:str]
    pgp:
        - created_at: "2026-07-18T23:47:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//WZddVAbmJL5PKAUdtuY2ZXj4CDiTxztRVH7utsjHCM64
            6OTHrDZTPl8vwhdjG7C4sqsUL/5NmvpJrTnf/pq+gFcNxFtwp9KvD3ldd0P3IsKv
            /Ux8NUYPv0eMyuhPOtgd74rBQmqavHjlBdohz68+OP++NuvaeAojhVNQKdbStVQG
            IpiI0X5blCg0Tnn0fImaD32MyZBWe0onTCqboJodxBhKlfd/A1qhNChh8stqXbAm
            dywOocQVOFwfAjGJxXWKzfyolAVM6hGHiGXFstyl/FRQFVLSP3CGYEufkvYv7HI9
            rIGl6h1s18jbvVj0zQNHF/IbZzd3cnuJHOvaVSBgYam2BwxDf/J/yKzPsRZkMmez
            8Zq3xwcVOmnZTB6qoaGQhAnugopQMMX0C9E6MJpV31ljadAW9+TbxVF5la89dcuc
            RSsp/hl5IjYJagrdRRkLwA1BJqg3+WkKtqWM2RLg3oiLzwhSTLez6iUVwnNMP714
            k3y1AeDnNDvblh0wJSeHAoe3YUXfoAj9S73GcXAvL8M25kpxJvJaH67F0PLcBhGT
            1ZF0o4tqIzP2Vr83wStVf4ZcmaLdlfEAObdzenGKkJLS44fzfkV8hMjmvMQpz3zk
            CaqqP4kMAFAWFCkTqQWbyRdVaW9qYHA4OsD/xOkjf5UBroY1H0OoF+R+KTlE7xPU
            ZgEJAhByANFOCqvpLyZFjYhNSvnixvscVsdx9wbe1aGdCJosUg3zTvg7FAz+O4G5
            bo0uwsE4qcOy31biTOD4Ew4Gzb1JjQWu3aSfkb3Yc2RW51psdEeBSeS4owsTIETA
            kHZZTcDLwA==
            =O/mt
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
