apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
data:
    clientId: ENC[AES256_GCM,data:U4S/ZIiNw4F6QBYzR+kD0npIPoaVcY4e,iv:6epWBqJ/oJ9IgVhfK++zufm+uXBe1IEuHteIcLekK04=,tag:6lr1xc4ErdclrM9TRYIBMQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:AS9BEZJMLv5LcrbVDf2NOmYL7KvA9Hzfr63NNf7ewoxQ6yDxBsBl56e1yxW/qi58FCE3CMqfpWgoNKUeUBLUAvQm0TrRxO15WnzZYWSdl8pyDjlBuLIEjw==,iv:KJqJyPguXB5WNmgkNR78Wh2zOgRmtoa5DxnykcEFZMA=,tag:iubLvxJb9o8MvECj81MSfA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T23:38:36Z"
    mac: ENC[AES256_GCM,data:EzYFNrztJtuabzDUA9Y+JbhmSZHwNnmFQ0cwdffq9eoEtFg6KyOYLcTVTfDIk3PUsS58exUTw5VuiD2Jcc3LUe73PFPg9ebSHG5hqVpTzddMdl+KWof2fCZoQuV4G7f1DrMNhydibFUX4GSyxnOtMc9uqngZJWyGIAoZa2J1xB8=,iv:iKCwFFuHmbUu3d5nxvwnz+PgwuLTgdElwEhSYc6ciSI=,tag:HFe50ULQIkNy/F53TYgdZw==,type:str]
    pgp:
        - created_at: "2026-07-18T23:38:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/7B5wLCS3vlhoXxydIaUXtF7TW6m2TLxKiypXZe40IO85P
            Rsg3mIlQNxQ5/drfXhibHfAIikWiy4IOT+NxedYAFcp5WKhw3FWjR3fyflXJrxX/
            jDHwbfHdU2/cw2LU8MHb/0Wxf+rP3lRuaLTsr1JfthThETvKQi5stzb0eiSAd6uP
            pWKeYMgg1DZT3HV/Jh3frwiDyxtOn4U7807DwXSRw4LMP/7p2vMx/NqA6MiNNQwV
            kVVxEBseO8ODfSGyXPPR1J7CzCwp7/o0Ktr+4XrCj1fIeFMS+8CPqPQr4Fe4FP8A
            INaxDsNhUUafnm1gnZ9vlzx4g6At8JvZJziMumJ9xCDmVTACmxUkYT4+YzF+Qnup
            TETMPX4heSvt8ePoURuJkajKnKd0RMrDW24gRTumLxf+jxDaMv1ebf1EK4VQISQF
            3b7QuF1RG38eiHzPiGCURxeQlJwmhZDSppTIqYNB/BO17lxaWng/ucpqA7vVOCIk
            Tuck6HNEkZVZRW1NTXaIuO837w9w/QmTCIgvF9agj7rwaKIXnUmVZKPKg/FDQLsP
            pI2eH6nQfAbEh7GyKWHO/mIwr/ta98xyjBwU62c40Aif/gV/D2hiiKUHu6TXshga
            BYSo9aLiFVOH2nNshrlnWWlkAvA/VpFSy9vtRhnWiAfkaMalgRhP5/GQSn6IzpfU
            ZgEJAhBQsXX0mRfEAoTr8TTZ6tpekHdpx/3IP1SkDXaAFW9NBGpHh2kzG4qmo1p6
            q8IZ2YXmHFH95T/nPgu75+elMV3A9X91Fz5XMwHYTu0SS1JfeTF8cmVt3w2Z8drP
            J57tcH53ug==
            =Tqkp
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
