apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
data:
    client_id: ENC[AES256_GCM,data:PQK+p12Wvc4UOCIT0pHINZ3X1ry9fnmc,iv:SoMzdhZWwUHuSTzIQdahZf1LQpXktDnpPp6m6q8yO/Y=,tag:BAi5B2rCd620YhlVx/8uQw==,type:str]
    client_secret: ENC[AES256_GCM,data:rAeSC/67OSb+bcWE+vfrliLwlfbH1IwD+D0FvWmXU35Yx//Td5d+IRIuUjqNDxk5e51QbBidWJ8sXPw8fwk9NL20qn4llm9p3rfyrndjmpH/NV5x7KcYZA==,iv:BtbmcFk3F4wCF8/xmQCTzi7BRrdJ+0POrbg5fOwrFiA=,tag:7EX0Mme21xhySKAFdEEHdg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T00:04:09Z"
    mac: ENC[AES256_GCM,data:YkfZjbgnBThUIzLyKqJaPsz2NMULJ+325zMhgo9tcFKlXpKU9P7PblMvrSk7Sc3PHfg9ma/xMDlOQIobAiShBy506ZYRo25J9y8OYiTzcnMpyMvVjia6pwozS3EO6HNAlVKfdniV1DOF92/eU1L6W99AFfLp3OY0/yUthqRCRyw=,iv:i8+5aQkCUJEKJNS6slRuWNVbmvQTmLPw61W4oS0rJbU=,tag:bXSDcViKGz+kLarIcWOc/w==,type:str]
    pgp:
        - created_at: "2026-07-19T00:04:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//XDq3zDqn5JA+lIAcoy9U5ZuJ9t8WPg5FNB/NglYq+Bb9
            MoMpEP7OHq0VoVFo3g2R0Yyo8+rYwr0ZMhn7Rq2So1H8ELtGLhRhYxHwMH/tSOj/
            m+EMXicbRmJKI0mqjONyKOkaiFc/dP5HSeSIPB68pLnHB7LBWStSbNVLxtXHVWd3
            Mr0wiW7n0xvO1+KBOhjm9DMyja4jARPjoivYxaxZ9wHtTXMZD0l9gpPZLuVzYgWY
            170K59bPRvapWqlInRPcBb7XjV7fax+oi94QW4CW/MrjZsXCVifulThnlWfyNe91
            Ap5TDPNIzfJg/36iE8MSsRKyA63txXcAM0AQkwf4yAUPq21G0S+AUltJOi8z6sDQ
            ItWBHLF/q+7IYx70HnlXKUVZIYqs3uOwtOnR1s1j/D2F8AlALcsnNC9pnV0L3O5g
            9hUoWn4ciLXgUZJFPpRXx4IBW8ThaQFnpSd7e36V1CZPlTYcwzkkrZPwOqNBANdM
            FxM8M/AclfDjjZZpUDIEmrWaKoQ6TFRay6s0RxwXsPy67PJMqn3Y+ORFb7FvsNrd
            C7qJHXqBykIVgwUCtIBUf30gGT4pe8WdXiO1Ts5c46KSx3bMKNSJXA1UjuWlGrin
            AWatKAxtVZC3I/MV931q4ys0GinzBzLi5NZWwMXZQN/4oIdsKRppjFYus+6sIFTU
            ZgEJAhBDHXKe4l4F+z8COvnTrC6thc48NK6Hfs7ZkTEOM+eEwSDXamp6YFGnT48g
            XTyhTOiB81/97eIeBzGdk6JQ9mDiFWNhCb3T/vMSfmbGJibxWqSSQMDJDiWpPL6H
            VMOuUoLGgQ==
            =ZGiV
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
