apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-ha
    usernameSecret:
      name: postgres-pguser-keycloak
      key: user
    passwordSecret:
      name: postgres-pguser-keycloak
      key: password
  hostname:
    hostname: https://keycloak.herron.dev
  http:
    httpEnabled: true
  ingress:
    className: haproxy
    annotations:
      cert-manager.io/cluster-issuer: acme
      external-dns.alpha.kubernetes.io/target: "97.117.2.112"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      haproxy.org/ssl-redirect: "false"
    tlsSecret: keycloak-tls
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: metrics-enabled
      value: "true"
