apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  namespace: keycloak
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: otel-metrics
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/crunchy-otel-collector: "true"
