# Encrypt this file with SOPS and save it as secret-database.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: postgres-keycloak
    namespace: keycloak
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:e87XfeKoYbQ=,iv:29CVIyq0UjCes7iz4AjnmRkMK/d/lNCkIWZ6keVIg2s=,tag:xz4pvBjr5eZbEu9ySK7UgA==,type:str]
    password: ENC[AES256_GCM,data:rEdYODZCPFK9XdMuKRvyWN2VXYE=,iv:TSDc6c0lUQ9pcCHTuhrzR5fckaMr8O2wYIwBtF9PBq4=,tag:h+qB+93YWENx3PBnPgnXPg==,type:str]
    init.sql: ENC[AES256_GCM,data:i+JSvkQCVvjmoXqEqoFTQsWBwfKB7HksX+dia7oIKTk3cRIPB/4QaV4JXlrmufWd36scmf6XvdK2UaConEvP/JnUsVhn+s4aTLuATDzLTMHT67/1fPMvCy0RvPW6vUIkTUl9siQGy8Ho/IlVa7B3x9cKFQIt75YfCd30iAvn2Mf6/9LY69xeTQo1UXcKmE1+zoJ1uaMQ7rN2Didlf/P8tc6K5njL,iv:oOKinNBVlPNCD87PxY63u6ijnbNSB5LitWK6ZP690sI=,tag:yGXiphVP5aqJtTwjvh1Ldg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T05:52:28Z"
    mac: ENC[AES256_GCM,data:xxLgVG2ZU6O8FRcf9yBmY58lvgr7RniaPYs20ijxRfzkR7pu0wtEwOJOE8qDUKYiUcWdx95oVljPZ3lj9I9AhsqPUTwcV2R95kU/PIQ8LuIHelokdPHZy93H6chjXWuuYTpPmbvtfgAfmKp1HF9iXUbNg5KaXOIoQNNvfrUjdME=,iv:LsqLExfGfJFKV0d4L7GNTx98nEA9KPvo7IV6Q+8Bo+k=,tag:ToUNLrMvbMp7PTKDifsl/g==,type:str]
    pgp:
        - created_at: "2026-09-07T05:52:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//RSrBTjlx8XvkYSYtZ0ue0tbAMlbF+/OT91Hsb6YShD8M
            zFocHvnmyZVwWr1PWShuUh/H3jJhTLtnATXYhIgVf7Nq7YMwVMu6bt2eC6bbTc/z
            6y7GxwtiJ5Yz3+8G4FAM+FcNeo2kcbYQdMvPUYkfUJ9n7M7u5KCkiKhWR38yPx2p
            V7srg8gKcPAXmHkJ3INQIStYHcV7Cwv3qW0YyM5gjrFOgN+IEU5cb7CUcttYZMww
            TcnA7VKBdQKx+RM/eKokqRvUcrHt2dq7zHPhRZDykBCeg5oX92++X6P8+COWBi0W
            uYAB832279gIQ1MAtkdC8Y0cgiUkOhLTdI7u3bBTJrbY3Wu0bAd/3k4tTndTJ0Gl
            E9i0vUn7DV97idl1Z9PDIu5QQGg6WwnZXD7WSij9qgYvZdtZrxc/lyVdHxvKHTwE
            oZ8McomiUwjoK3oo5RdvsvbjUmduAbHZDOCHTh+H9Q3Wt2AO5t7W6K8kupyqNV36
            kBQCC6H/w+1BRFGHdGHUCN5QI2/bW/lELcjDzqj6BFjE2EDgwIlwEwrT/FHx5jdy
            TOCUk5WDgxLpA8YSMv0rcU3kJIK+3MYwjiQ7ELA/++Geyt8N38T6EUl6JxrdGNHY
            Xrh/Xc762+I91CCAnysaLVhDH05U7zLRr8d+r99nWNfXObP7+LqxfZD/GUYxyZ3U
            aAEJAhCBXHJ3vwbQh5VMO8UcxcHp+eO/mdHgAAJ89G+e9YRcOGSMgttKZa2r4HXY
            Ncz9jh+zcmivklBG5mivqhsLHTOVIQKg5lFurvqq4G1RDac+HuB3CNOJgRwEfKlC
            4jy879B/vk8Z
            =TBuo
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
