# Encrypt this file with SOPS and save it as secret-database.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-database
    namespace: keycloak
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:oSQwz3BGR0k=,iv:c5NCFIJ6f7Err+3nqYK0y2EoAJonbelfzm6E/Rok1Ys=,tag:bfZtvIp84btuExgI9Fy8tQ==,type:str]
    password: ENC[AES256_GCM,data:jBpefL9qJ4ayFlklXaxRrdA+KzU=,iv:/yNrdTpeg/pV6ZH+KE3tqKAH7Pubu1z3AZ90QlvjDBc=,tag:m0N4dVtrZFS8tlI1/irkrA==,type:str]
    init.sql: ENC[AES256_GCM,data:V4ZjiOpWBx3BqrnWIPr8w0s2D3PfGFZB8pKN5+8NEAmTK2agYHYh7a0YmfeG1fy1MspbJLp1mWe4Qaj5uNOuMaRVe4UyQBbBS08vzJoF3zHAlp0EQdYXMwRgL0onkpoyO/BWiWRRczpj+m4o+k6h4NIEjbo4EbuciVnsRpbZXyOCkVZZvrhm7ABP8H6a9yMvDJ0/a8XUtZSJvkCcxkGZMmoCFzm9JrXHjXVOU270Lt3BMKkuZakJD0gLU9CMJOHVk7HXp9DXKH52FyJywqlI60OyBRVjz5P7dfkg87buJEfT4RHXC9DZW/yuMTlUHodlNxuu5pxR4WQ565/TLD2tUoVAqAQ9DTrWANIUnob1d81OfEACaG3PEOIux1loA5KOkb+zug==,iv:tachRBTZMx6zV+OcdlLQEzk/OSIdvYDuBTN95fVnOcY=,tag:rm1fBtr2qdYLYkjzQdV+6w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T05:29:22Z"
    mac: ENC[AES256_GCM,data:SMwKhwCUccF/Otj3qRY8xGB+RX5EwN69xWqS+yBvszY80s+8X6EbHa1grhVkWzPjOMRhOs4bfuXgSTpjFZ+Jr9IkWqUNpagTzsu0lMqJcApeGwdcx3fKtLISUJVQ3t3RdRvdbs9G1I32nPmMfV1YN+WUpY2I0Z7DZDItmQHRj/4=,iv:1pwsreGdXFzNrXP+AQI5uZBkrM6HSwZYp4zF1MfaaDw=,tag:WYJB055YF1kyKwbp6wVT3A==,type:str]
    pgp:
        - created_at: "2026-09-07T05:29:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqARAAnsvwFyORfbxOHxt0Uqxyn/eRGHhjBDp9CgEdKxeHIq+b
            clwZK7TX7UMvIWg0vXZTdCXawBq7eHOiu1qntXnTRBt8qovEKlxCbDwKHmrjhx//
            S0P9i1WrLd01c84vob5J4dqpjpjl85JpidOwUHHgtiiIKPVq2BdwkoYbw1B44Mfs
            esfzgMrRMRODoKKPIWzSIx+QEatOkFD/v9HhJgNhwEdPtiuleIYU+bTewUKIkuNh
            U+E5Gau1dsW3Pm4W+XJxZrRmUFjdKkeYsqDaqVdivyWJlFURFZOVdF7Jw987oHu0
            oWKBln47NOmaGH2IiBNC3O53swo3zz4mvkmnMqAML33Ctih3J3WQ5Qf/+LqhBDnD
            yJYgGycd4CaLw8WC8pxSOg4zHHcF6J5axgrRIM1TtLdTdrzJtd4z9Q5FIGfi5vBo
            djUa/+7hWX01sG5KaCDee4mXA3UARB1ZxM49ZF3YAj97Ilh2XDY9zUwrqeAE3opM
            VQP50xhI8YxOYJp9kR8WXU5vjccISj+7Dev2Mu6ahLZJ+FdjuIZivwule7ffikCV
            O8HJAU6RJM614wbMN4gYs5wMCyLpzOU2fFG85X3qK4O6HDl9aCHKnvVngSvZuoi6
            9KywAy8pDWZaHOEGfbixQaEQqXeAr5LBD7apGALI7wmkkLc+ghKvq01dnAVKdxrU
            aAEJAhDt+ypa4O/x7uPd+3SCn1Pz32ky+SAEb9ZeV1Lb8imLZP0T63yrbO5Wwcy/
            Res6dVKuItwVhhJ0BlXLRdo2lPBkJeVFXEm9xoLUf6NI0qB9+V5rfgMAFbNFE1LI
            JkO5I9Ci+nN7
            =06LE
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
