# Encrypt this file with SOPS and save it as secret-database.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-database
    namespace: keycloak
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:VbAwzKi+Wn4=,iv:hvJi29FCGZj6UApE11buiMqFsmAH5E//OfaH9aMKlj8=,tag:njijtWJAGCAzyoHwRK0ISQ==,type:str]
    password: ENC[AES256_GCM,data:0ZjuIhZ+BMuHJYn1UNRNePIseDI=,iv:aP9r2YufWIqTVYhvEAdVMhny89yHb7fgb0Qrr7Kc5pg=,tag:iOsXbAuqDk7JRNuHaiYSVw==,type:str]
    init.sql: ENC[AES256_GCM,data:XLR2rMJwcCJLmh6dQMIO9Redoo0+DR7H+XF/Uh+eSc2YSK1rbr8TVFm4FQmHaI+ctJ2H93n9awbR7kpuXsgNY512KFoM1aUJBYjycHigiW9og9wE+1P5YTv843/pThN3tWHQPzSUPU4mz/yZ2YdooPQrJl4Rb7fuky08wGfmdTSvuGU4GHSn4wTHOpDrMmkViO7S24z8/X1zsf7fQ/fBmTeUG+thIpM9x+APrXm0ENyV3lf9mKnA8sJP+i2FIjBgkFTr1uLR2j/gaxWNxceZ,iv:LNihfnZcfPp7x1VHXZs8vS1QSooS75v7g3tWkqUxFQY=,tag:O61pDKoqMmZ/mOft8CA20g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T05:32:04Z"
    mac: ENC[AES256_GCM,data:MURaT7jK9qwmzner9lPXMslqnlXsP+dGegKeKFCgEO7H8OjfHTGMXM33PEE+Vrubwa9IHYXIscyqnxfe3VbFgvqCGTDiHPCrTG0x0ATWp6vKPUe1+4JnpyhKnXwSoM1uXiA07IIOcd3ISdpzz9ONHMY+at5GxNXPj7jyuHSDGWc=,iv:5m9ySGLi2GimZkTGK6yDD+i8hwiS3oYQI7KtcJ92US0=,tag:ix6FjlQ0tqlLO8vOR/xGqg==,type:str]
    pgp:
        - created_at: "2026-09-07T05:32:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//UmXdfPl2oWCXrDwmkntSOAqohqNIrUtiSxTpsYQBZPaH
            3DUVATARTGlV8sWR66oDLvwHezzLlGFICmN8gNiEt1VwRRppqlFp/SAKxdCW2twb
            dxOFmG7NxDf5b56/W0xm83bSwkBrGJugYXqFqn+hovj+xM5CGE6rWc6qzDojSZJA
            IxtOn652A9L53Hlou0iWo2rwkafnV7yciX8MAdoUOKOhZYqymwb1fVw3j929NHGy
            nYFJli68NWSXZ+fXO0v9msYQn6+aHpU/yxOVzP3IzbJdaNmbKZwxOnIEROQUdSgB
            9qZM4rvVf0JcoG2XpCe9roDDurAfzJlxnN+I7ilT2HJMTTlF4ZhqiwYtsl7SM4LB
            6EsJyx3jJ5pF6jtAvCR7gJUFOQOJXsgefmj2hZVFz1R1YyVEFci9VkIsocBwHKtt
            XVCYFdFKgbstNThBIKt8E7gaGliHPHfl4Voj44c8lgxqRTJtbV3b3bqpC+VowlTS
            yfN6Xt/WOgZLNGyyoVwkMFqmnzYR1skqhHiJgSTfA7TY7BMEs93x+FUehACHx1i+
            O+Bkfut0A8AS3Zx5Nt1TkVDEJfA0CxPG8pSEMCxWX81EuXEYi8SvcQ6R5Gwt+Q53
            o09IntNH3TKaXgfDS78UdNR0nxKAP3aiA79hwpgUl4KcoFtRJfvVqL13skzPIyzU
            ZgEJAhDWTUqxSUJ0xKIgn6/EX5pYbHyHPcTYzVk5KBbf6nQNZMsLU5oykrXT3GAX
            SS5EZ8Zse3JWF6+EMY45KWx63no8xCgtvroT4bS6t2tsTQSC4ZeBsGraHWInhr9j
            1ymxTiwsuA==
            =uQpv
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
