apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  namespace: keycloak
  name: keycloak-database
spec:
  managedVersions: true
  scripts:
    - id: 1
      name: create-keycloak-user
      scriptFrom:
        secretKeyRef:
          name: postgres-keycloak
          key: init.sql
    - id: 2
      name: create-keycloak-database
      script: |
        CREATE DATABASE "keycloak" OWNER keycloak;
