apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: grafana
stringData:
    client_secret: ENC[AES256_GCM,data:Tpo4qtA7qAAFEr5fa9LbbDdnqSqghn9Dt3n/v8PgAq8=,iv:0B+ixH+gpmvtzE89bHE/ehDdGONCskQMGIE8seiBBH0=,tag:O0jTT8nve4FVLgY381TKeA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T03:56:36Z"
    mac: ENC[AES256_GCM,data:cteQq6HD4wD9mDZ6DOaWAqkRlvEp9lkA8Uhth/7HCGXXU6xVNZqahCl/eN/0Hi8TnWkbvNMf9BvS8aM/y+YKYOnTpz195ioT78XACvwqg//AbXDYp8K+piWSqaho4JULe6MmDbMMCRMi81bmTzDUacu2EOcNsKzvHnuPi28bXXE=,iv:R4BwcjraAGqPL53+Vz2QWWDKPIUaHXCQ9pxJnBBxDMY=,tag:pNDXY+PuK7fhKtvK3msu6w==,type:str]
    pgp:
        - created_at: "2026-07-23T03:56:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqARAAmhJxLhKsegA4cSLs1SWaJkDRhd4680YcsrKCCt3eO2JE
            HiYbacTxWTgyhOEWF3ly3UGc1lubDJ6sG8og8O6wf4JCYRiJ4Cb+ZkDrIHSDNpc+
            zGstrpCghSyaE56FKnfTBcK1WXV4VBsI0riteKMvjQPfPN461rhzANf7LuSPQDN4
            bI1lvpIp7yuWAqvqbizUuBfg/HK2xchDeeRVp8a4lmkGlac5UDIgME/AK6cObCLd
            tqbNmO/B0dZSqvq8aVjbgr2mSfMc6jAkHgEOvce7bx1JJuaSOgG+G7ET4U2vxRGb
            CCawdAfBZdl2ylQfWHtBE37A/7DTGMT7megcs8IrAEAxNLkEKdcsnw/i6LOO26G+
            atKaCfX64mQ3szeAN0hgbnj+WZshjW8W3vdACZTJ24MSul7phPU8g5QAmFhflHeA
            YHSS1mSDaMd6zBGX/5DxRO8VQtr/bNE3EBuuhUo1ku+eF1qj5rp+PZUlUo0r2dCo
            fEpJydMIr1gRAWj4c6rjR6zxhb3S5K7UL5d2JktbBT2htTZLNGjORytr7VUMzPLf
            4IxGVsbmIDVseJvz9fK6CNgDpRS1bnN4SlgANG7jLaDQywoGDhYnRL4S/zTzjQ+L
            l/V2n1lMAo/bgWEdgBTi887Qa1eYXwSUVlrJ1tdUUpeUEhmy71wOemh+g86skQPU
            aAEJAhD/uYKlgA7SAXP2TwVPN6HSD4uDaZpyvChQAgCWlNkDNRw7ZFOCdYaGydAO
            nneWGXzaGGGK61g176evpadfmeLUiepcxPIJSEAaHT7eUkCrbPmuyxjPTIAfBDAo
            3D3Tvl1HFVNp
            =1bmu
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
