apiVersion: v1
kind: Secret
metadata:
  name: bitwarden
  namespace: bitwarden
type: Opaque
data:
  adminToken: TKA5HP8j9Otmo0SJKq244otSqIA20QnnHFirWKlLYJre3Gs9IiWSURbMBP7Vl6md
  pushInstallationId: db1eb201-ebc0-4001-8faa-b10d005c59c7
  pushInstallationKey: SrPQsHQNLRLw2uLbVlYE
