apiVersion: v1
kind: Secret
metadata:
    name: rallly
    namespace: rallly
data:
    secretPassword: ENC[AES256_GCM,data:V9GmqOKpSGzwdE1b2pB0g5X6c7Gzxqn+WJz4HxddIv6OuF+DooujWtvrqHQ=,iv:c9pu9RESF87w/RWbwbCw2hMgiw9suGpNilCNbFzR40A=,tag:RPrmtlpTtlKHcLwTUWxH6Q==,type:str]
    smtpPwd: ENC[AES256_GCM,data:VMj2UiQz6GUbcVS5MKxxV8hBX3PsEF0H,iv:t+hoy+gWhwX20nZYZCIfFivUtR5ndRRU6gTOGKcveu4=,tag:pths72ieDeTysgVbRq9QWw==,type:str]
sops:
    lastmodified: "2026-03-28T19:02:47Z"
    mac: ENC[AES256_GCM,data:a9b3oF1/0FvVzvV8PJXYHT/hZxx35ziMPcfGQPEoWNKHaw67smxYhMwU4+akhbdxkufEtAWgwYUOVVzS0YQlMZ9zWv9vPWpT4fmL0g7MDshwmXTLWK1Aa+HVvw1IEt0CgX1bf61pkDZ9wCICpNSHX5i6jyvZus1CUhsSAzBuuHU=,iv:dOQBCZa2F2X7kbuvm2EwXbYGPtq9CjBXzBejAuniBQY=,tag:Ujg9Mb1sBApRCCo2EMqOJw==,type:str]
    pgp:
        - created_at: "2026-03-28T19:02:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/+IvYRTzsN+SrEEnTb5ftQ29os6e9riTE9s3RPfSHIyLoD
            ZdQxLRC5lx/2TAKxkxPpDDNYSQUcldy+ok57xJdp1jdx6t/XAMOkBWdmU+OwfYG1
            bJUIEKVlphrc68tBLQzx6UeySz9IbtnQO11kd51kJRmgXWiToeE1lxmci50UNxTt
            DWkk0eHQm8ZcJXdSFOBSrRb4hDycrtodP0Efb0RdurYi47TTv7fqc74mdb7QwKT4
            3Fy5VlJwyABm8eMG458m4krYXYY1YEdD7/7a1sDxSlqrneiZNKJMOCHiqxgM9ru9
            FE2mS81CH2QinZN/DAkec+0ky6sMJMHhppMKaK6xmHiJufIiyKPpx7cv6fmmkUU6
            S7AXqZSzuO7QRdpiumJr9WH6L4qFuzrmZhuOqHHghLTX9rDr21Th6hTIAupMsrbP
            QFbOvjXayeV1UlWoSgZXjRvdslY3pHeUmTgGWIrdTyatqQLn3FJqoIvEYXip0GFX
            UhbeYZgK0HWlhopjnPtVTBfdSvrooKt15Vd0+nx4i0esV7+6ZRbDV8ZMEphcc2Y9
            03X8bYX2L1WLtVypBVSKUnQOXJflklUdL8Po6uFGZK4CEp4jxlMQ63GB4a/W9z7R
            KqtjTkV84LUdC/ZgScxMI+0/0xYZuqJazlCYVquwjygh62voUf2BamNa1Pgqfy3U
            aAEJAhDmaEi/k2etbzcFSoPm8wLAtFNNABd4Hvtc25B8VZMEV2i9w+xKpD95POnB
            W5Un9jzbPOrJR/36eef2YYK6sYFl9rnBHXdMW1WONG39z83r0BgyUxr5wlnLIZh4
            Qy+PDEG7saX9
            =B5jX
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
