# Encrypt this file with SOPS and save it as secret-backup.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: stackgres-backup-credentials
    namespace: rallly
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:f+99P4TNOpeDEgK5dPkZg4M=,iv:xJSKMPH5RCQ1O9wHoZxls2BgaUcswOOoW4rQNklak5E=,tag:0EohCeQQvdtCVOdH5quMug==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:p/h5MzNxVF4+BBrejAD2TJGDLtsXexH8mHnadSLs,iv:NXCGOaWqN5syzCCLziZKJBHlSWw3w8i5eo8jIetobVI=,tag:v93cvB7jrnZyoxZg66M2uQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:33:10Z"
    mac: ENC[AES256_GCM,data:e5JKFRepbJbCe2CaDvgkEYIPIay9Qc81/v4/IYG9jxN9R7+5me1CefzBS/BH/z3scwOaRgScq5XAq8ZXCACVUP9QyFSwngh0QONxH/9t4z7TFBI0Psm7JW6VPZAHh+lxW4Li5llfo7T2eEFC5uihcm2wQUk4W7f53w8Z+C9p2NM=,iv:5lM+O9HnsB1sKLZx/Cm08k8vwTltN+vqzecqqxg9BdA=,tag:0TdWUW2jGkn1cZnCEZbpKw==,type:str]
    pgp:
        - created_at: "2026-09-06T21:33:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//Rd7WSoFy13jjXfdEmglEyXZVLLtWGO+HLTBSOy91WnQU
            LXMWQhxYWv9HZ5gws7s8jiJPnnaH/KuYGatUiWO6WXTVsBnZQ0RlW2OKlX88+3VY
            T+yjHsFinzMNMr7dThuhOqmYeVmK3s4RbCdkMRmAbXDNthI5J4pL57NZr6fm2O6g
            rmRzYCFkznPnCXwRUdlzTbgJ6m3kRpaqO8hcy8o8T7C/BD/TEli4FVMvShg9X4PD
            W3c94XJ7/IJMvjuqJKMcACouwjyZzEOVQ4FpMKenYP8UDIv3RN9LBYrEXkr6eFdt
            6GBobsUJ5YbZmKkU+Ywh0eZOmGRxdvYLyRu6Pt0Y0zQMSGk2cLmP7/g11qHBBiCD
            zwPSwhu4oxjCduixVHqndpfpM5Nwt0fxHUvoZLqUICuR0Jc/025Pjs4TzGf+2MNv
            vXChQet9P/BAh6tnK7QjKqcceic1IiFRepxMjVHepjyXwl9dNwonN7uI93sbzlLP
            t8YTZ+YGy4R5hXk1a9039aZ5Zyw34VcudzB4pWkWf8CYKjtfYs9qUQ4EDbDg4BhQ
            zkBkZi+xbLrRG3DRrHCdakl9PZjEJlMGF6ORh8Kr5VDiPQkimotD7iQJv8AIv1w4
            Taen4eaO0AKK4y1xF1SR0acbY+CQs4Gd3v1WXfe0DNoPiT7OIJuEqhBoQNGkzTzU
            aAEJAhD7rQhmYMV4+87D2qvVqs2NF7pMphUINYOMMT9m3aCR8yQ2+zTP5wn/MWTM
            1uxv3RzElnJ2oPbp4o85AFkhsnGbIgxWG5HKfHC21J6fJKnVGyAD35fo3wtU6S/y
            GyfNKfdh36Ha
            =syju
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
