apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw-operator
  namespace: openclaw-operator
spec:
  chart:
    spec:
      chart: openclaw-operator
      sourceRef:
        kind: HelmRepository
        name: openclaw-operator
      version: '0.9.12'
  interval: 10m
  # See https://github.com/openclaw-rocks/k8s-operator/blob/main/charts/openclaw-operator/values.yaml
