apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: istio
      version: '<2.0.0'
  interval: 10m
  # See https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml
  values:
    profile: ambient
    autoscaleEnabled: false
