apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  chart:
    spec:
      chart: seaweedfs
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
      version: '<5.0.0'
  interval: 10m
  # Defaults: https://github.com/seaweedfs/seaweedfs/tree/master/k8s/charts/seaweedfs
  values:
    global:
      seaweedfs:
        enableSecurity: true
    master:
      replicas: 1
      data:
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: openebs-hostpath
      logs:
        type: emptyDir
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
    volume:
      replicas: 1
      dataDirs:
        - name: data
          type: persistentVolumeClaim
          size: 50Gi
          storageClass: openebs-hostpath-retain
          maxVolumes: 0
      logs:
        type: emptyDir
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi
    filer:
      replicas: 1
      data:
        type: persistentVolumeClaim
        size: 1Gi
        storageClass: openebs-hostpath
      logs:
        type: emptyDir
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
    s3:
      enabled: true
      enableAuth: true
      existingConfigSecret: seaweedfs-s3-config
      createBuckets:
        - name: postgres-backups
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
