# Encrypt this file with SOPS and save it as secret.yaml before reconciliation.
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:ncMI+xuVsFseImVDaW5sC685zNRE6EB1SkWiEFeGOa1lYdXRwZYPHiN5VOhsU8FPZYVHpbdOsWaV1AwWQ1lxcPoVDq5Oh5TAPGegdu7jTgoVB72BEh97WvYGaVvB/QcWT0WqwLqqYVhk9dy0azzy+8dMGermZXGgZ4INWGz6uA20WqcV+pN+H4Iy09qZhQoa+sMupe3PTVbcqqAdYqwSjMBoQeMMDZXMV6DKJfg8DHhPuBw4DEkGgYx0flCk6UkFnAatXgzeNof0X5TATM5i1rPu1R1Unb/FHhJKynVAT49349ni/eZ1YQ4YkED8UKgVpnu+f1fHCcXpVixeKaUbrCtlVdqBngj2Ml/iAUK+321pDewoQagqm6Y1z/bCw0sEFEaP2fQczt0Nqfljqg7RwGhfFYK+hdkd+eiguqmh,iv:Qqeamk7jq+YKyakrrQiJuIOuoSCmCpRKH01jYAnUVu4=,tag:oM99fXNrkUsYzP6h6hppKQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T20:45:55Z"
    mac: ENC[AES256_GCM,data:75YbbBQ88/3noeJAtXh3vLb9HkBVUPedPtiC/AVf9XiIiQXcwR6yZD3hJ+ZDznEKoktR+RdIX+3K96tjJ1QJQ4XlXx8TSjWNAbiX+NK0npBhC0Jp0Y9UgSm5U7RHikIjV4VfgOs6o58/v0DQqmKDMU57A1PZwb9xlfD1DA7fEdM=,iv:0JU5JvKB0V/nbC6/9Y4aiZNgNn5uCkORvyRNNST8CAA=,tag:rox7XUYZSW0I6EDIwNliXw==,type:str]
    pgp:
        - created_at: "2026-09-06T20:45:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/9HbjJil5xNzVlMpbG94VfxG6kyg1l6taPmNX517jqwtoV
            Fxr/hudy7iqBC+uQFRpxQrAv2FNcNK8r/9rxLgN0x8geOMD4FI741+NNTNVUVuQS
            KcJZ2hVpFCIiOzfNRiRORsfL+pySWwObv59uT5E3V6rQlToYNLvJHF20d5kQwOaP
            Xz+D9Xzu0FXwZJ8RPSN+K3b/tlMfFjtpVs3LR055ZxlK9O9RprDv3F81nXqWahNn
            gKAB0ZdEBx2HWYLnaTOCU/p2KTZo63l7Hmi/k5PUcb856f2/MiSK9cqmnW7B1nXO
            3u7FXBjNbNowiOAz9XFjVqickvya+3Fxh5USU3T130VwFrRY1ZAe3sSUTLNvUxD8
            jYaoL0GTrx8CtajjF4FLx5O5lcGTf03YNOO1p3Z5gNe/8yATgSIzZSliCTl3PbA/
            r2c8JR+vJW49lBjoMznR5KmzINWb00jD0s9/PkzIsH+1jg8RtAMe/FRkF1oDuhdD
            1ueGEbqqVvD3tjboy9Mvde6yaHbv+PgAhH2fz0VVor1oZVETrD4NvmQQCuROIMW3
            sRpkfkgKAwdq2cnrOvKHzVhdZN3doERmW9g2msJIZOGbkd3ZJGM38vXx74RWL7+7
            X75RUvweasXLoaN5D5A/SOM1PFvjd1AqsZDxk39122gkMKSlv52G5FgRqTIVUW3U
            ZgEJAhDQEvOzB9LG5Ne3yXck58/jJ15B4s4HBuNC0lB//G9kpl9X+2HLf9KgZYjL
            WGnSxfEkhsmqSP4eVdFERM/6WJnbdmpK7Br7rMlEZD9btpOZm2C6c7LNirae3mqx
            HQL2P6at7A==
            =Aati
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.3
