apiVersion: v1
kind: Secret
metadata:
    name: openclaw-api-keys
    namespace: openclaw
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:L/dbtNYPOU1BZWZDNtvQS3VNSFdjoE7pNfPN1PLDwrV+F41Hffi3WVZgKSHzDZ/IIkHRSc6pGOz/EfVCLz6SyULnEioI6f46sr/wPgO5nwi3g+zAzOi35n3+zZQvDdDkq0s+0IFT33GAVHVh,iv:ygxbsrfufIdfhFqLODQ4nRuHGVb7TXZANkMrG5o2KdA=,tag://T2dmXHbfvQoHwW0FkiyA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:WVo6ktbZKWC2Bs0wThA6Ss5457cwy96nziuCjwGwtcOibj5eu8UeQUjlmPI5rsqUF6f7q6/+5bNaKaILv4K4bA==,iv:XY+kPu/oKp+46FwBAGClp4sbQiHB9KJTbVEwQXg12Rw=,tag:PuM24wNWYk+8mQBH//Q65A==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:G/PMM9IfeXHAgRS1RURGJek+aovm9bDRmy35C/UqetSRYUmyZ+O5Uz5sHC5TNmyJCDYXqU6p/BufMVU5gVknJFT+6QnjImck8e2HdysrGwARuw3GL8jqng==,iv:yoZ9mllqmbE/uDg+T0DvU1ojCPkJ16TraYoUQF7dGEk=,tag:7Dp1nIHhGApTv1VE+6x9kw==,type:str]
sops:
    lastmodified: "2026-04-12T00:15:08Z"
    mac: ENC[AES256_GCM,data:q4FhL7TPvOc2hSetQZeXmwfkfVwnfh0JeiIvFXuYpAWTFbDqpggleRdNZuPf6PPNdi3RjVk5hg2wlXgZhgUF5x+09DtMYeeVQfOqadtkNzSJxghvkfuFHqi8/JUWfSBsMZgf0rZgRSJDm39QCtE2QAD2U/+npuPzpjxybb8/1kI=,iv:9ZmBv4peXbpOqFZRKA5rFKY/ZiLuH32hCPW38OX6Udw=,tag:nHUDiYDAXYpa/BETtKFxkA==,type:str]
    pgp:
        - created_at: "2026-04-12T00:15:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/9HTEvdk/jdIT1eY4ycVbOnFE1RmPx4mJN38qM6Rkj66Ju
            z9i1CyhFHcH8NAukDqmlyQDHUnaOBqTMPK4CKyS/IO2ejDWa/fX7Vn7XcPfZUBdc
            j0fWkLr0blNCM/vMMYEhEZJc1EHplMZlJdwLH1Tuv9/pRtmfX3aWyDmyietbTjSl
            C3gUSF2ycCbuPhlCplfrs+HlUais9lH5mc1Rt1Twc30pdRVihGHbS+zH/KDWn4Nb
            sWQsf0vkjEdeKLkISPahy7pz/wDPazSt3QgM4IyS4RRG9NLdeeF+vxW2dGnpZTS5
            uyvpf1GzDGufUTNerVT6FfmkW5Hb0WSzPGZpEzWLBae5qda+cLEOEAlLNjXNiNyK
            5H8upjNt3gjn9PXSUMksdwcbwx6DIZaCkpgy7g/yxzq1KCgigGUtI0Q5uwT8JqAY
            IV4NHm7e4TrFJsmjypDmdJzjXP2eDMPfZWrnhqAxjgr8iBsVkGZ4oJwlyEG5tUv5
            PbELJggzlzpGoE9OjAs1mzHyPvoBBw766vGqbpXIq6ZPtiAv5jGUX2ptO5clCLPU
            3kosgtTKlJBayy+dGyEpgKrdWP/+8dNzIhmdKPkgsuPkK2UPuNwC6DMOMueukacZ
            LKZFXO02oQC0FR1t61oYgZQCLh/58ZP5OVmN5Cn5atpZE3GbnwyGnVkjLyFa+6HU
            aAEJAhAeotGdy6jdhXD6fnDjwudr5bMfXFNkbhnsTlqQAhJHk6FsDzjrb7860poh
            rnf1OtxJRaOGV8GPBlwBws3H4ENONslDul9LFjEEnDyNGsIRMZEvJs8xWwISw/Tr
            iryL8PVaBmxS
            =KE4z
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
