apiVersion: v1
kind: Secret
metadata:
    name: openclaw-api-keys
    namespace: openclaw
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:2FULtfxzpnlv9K3G+x2oNdcuxGYXJK7qTtokgL3AvGtmh4og6ECiEN1Z5HqN+syf2ZKnzUnzzcOXN4xcaJdq9ObZT6dzH5it44uhqo4/Tj7psKbL3I/RTWn4ZqYgn3hOG7HnO5yrQUg2RaPPIvQU3c3mu9OS2d+MeBkKcAs7lMBvov6WEXfOWBEGHu5bNP3I,iv:1L798m4I8iuT82WrODPW4aBZlMxPTTwgtQUXyP71K90=,tag:VUUzSTYhd+tdITIGO+p/HQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:9ETDAloHHzeV0yk7QKTEXMlp4p3xV5GqeJgF9DWpiPo51THWqhcI3nHvuB0MueHiVoqrQXB/zoFNfxVUWbuV8A==,iv:xVnXel3qN1Tn0jOoKvLCkxjgxJJYFH4TQH4UvLwiSlU=,tag:1uR3eLQRGdUO45+1QkNJ+g==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:LWGJA1gAqLVrr0MkABjJpHCh9cRsHr8GJ9rAIxVayFgJskJc3vx7wpCSpUuFgGkOhIAxds5VhbX5mNkQDiqXbUUmWqX1xw8OYoh3GnX+IoPfyxE6W1tOSg==,iv:5ezbox9I+gVWbOjfoHTfuMgOql95uXHOXntA3RBo1/A=,tag:SfTsiAqhhWEToNc/FPBv5A==,type:str]
sops:
    lastmodified: "2026-04-12T04:01:59Z"
    mac: ENC[AES256_GCM,data:WyUXNJW/c9m7UNac3LpXiQpLMbAp6fRmo2G8Og/qxNBlvMgpVStwp7m66SxuDDHKQdQaTZV0og9+SJvnH7Twbn/jp2uOudbkxYvBZLoyjptUjvg1tdG2/ykj+9DG5wucmeBFEWb5gGC2yZWAH1K9ZfAbXTWDIo0lfezmqqhQKaw=,iv:NlD/sqQIMcl53OQi/Yev/ydguaea+Z0pnRa4TqTvxkY=,tag:dvftS4KWFXID8321vV03lw==,type:str]
    pgp:
        - created_at: "2026-04-12T04:01:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/+KRsCZqT/2epQZEVpbYj4VqWzqXTjGseIV6PfN2+zgTtJ
            49wjMfvSz9vUbJiQin1YB67MoRxyuJHxD9ZLkcj7pX49M6faa7wdU1GmkLg3pTC7
            2f9H3GDNLjLXKdtz8FUYDvTq4Zf9i3IA14YJoPNLjXs4QZEtW7erNL1gcziRcAk+
            uqTRUygQXukkT/f0ZAR53OMMAYx3YZdiVY915vxNiKQy+tXQ2R/ZdGUXvG1uiIf3
            aiR4exsEyZcCTS8hWT1yEWaBC/cF+W3DhfVEjRxnkomoHhSCB74x3jmwcfQGeNxJ
            AB6Ze3bP907ne33FpDJjcSk2/ZuVHFRSPj8/gBRpYgYDTzAly9jp/ppxrqQzJpDR
            1IqhRNtf+OBmOEemsRZwBrj8mSb4b7MsUOH7EtL0jY6CjMyHG9yEwcQe7vTScKK1
            DQqXdMG5PMpZIDZB5m6+1j0DPH/dY5crxraqai/utsKNH2HmTVV5UxHP00/9AtiU
            pp4W92wN1U2o4ddUvlGm4oMwKWg3enzXr2FHs6/nTsjtAjiHPjXn1s46NuBP9SAS
            wf+J5gWiAUVIdDeRFmuEdzpTbHX/fKNGRHTuma0Yqodx0oUk9EbHFjrkGbPdqvJB
            22wjYJTleU87wZgqjp/1VuF8KpvqFZwPx0UgGDoPx5Em2iwD2GWBzTNOABrI/bXU
            ZgEJAhAZMMfmXL0/MPotV0HGcNQkwhZ3cwEVQDBeDUrXhEt34Iua4pyKJBnNRdP3
            qyfM1BjqhtB0HgnRgexpfhmjheWmdEbuTrjUBintaDr+vmmQio3q5wIslGt8wUXj
            gqhEWx11hQ==
            =/0rR
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
