apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openclaw
  namespace: openclaw
spec:
  serviceName: openclaw
  replicas: 1
  selector:
    matchLabels:
      app: openclaw
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: init-config
        image: busybox:1.37
        command:
        - sh
        - -c
        - cp /config/openclaw.json /data/openclaw.json
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      containers:
      - name: openclaw
        image: ghcr.io/openclaw/openclaw:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HOME
          value: /home/openclaw
        - name: OPENCLAW_DISABLE_BONJOUR
          value: "1"
        envFrom:
        - secretRef:
            name: openclaw-api-keys
        ports:
        - name: gateway
          containerPort: 18789
          protocol: TCP
        - name: canvas
          containerPort: 18793
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: data
          mountPath: /home/openclaw/.openclaw
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi
        startupProbe:
          tcpSocket:
            port: 18789
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 18789
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 18789
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openclaw-data
      - name: config
        configMap:
          name: openclaw-config
      - name: tmp
        emptyDir: {}
