apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 10m
  targetNamespace: ingress-nginx