global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:2112']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: timescaledb
    static_configs:
      - targets: ['timescaledb-exporter:9187']

  # Unable to get this to work with host networking
  # - job_name: 'homeassistant'
  #   scheme: https
  #   static_configs:
  #     - targets: ['home.herron.dev:443']
  #   metrics_path: /api/prometheus
  #   authorization:
  #     # CREATE MANUALLY: Long-Lived Access Token
  #     credentials_file: "/etc/prometheus/homeassistant-credentials.txt"

# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: '<Your Grafana Username>'
#       password: '<Your Grafana API key>'
