parent:
  claiming:
    enabled: true
    token: _dnJd4sGinPt-ZI5v3ZjkBrZG7cus8d_erZhSNDap0pDcehY7m5ujpPsj463RHmFZBr2MmTIjzhzYmZcT4gbA2L6uotTRaiOK1DQiXQsN9JmUa1OEPirh7nAZIVaQiztA2Ve3yY
    rooms: 

child:
  claiming:
    enabled: true
    token: _dnJd4sGinPt-ZI5v3ZjkBrZG7cus8d_erZhSNDap0pDcehY7m5ujpPsj463RHmFZBr2MmTIjzhzYmZcT4gbA2L6uotTRaiOK1DQiXQsN9JmUa1OEPirh7nAZIVaQiztA2Ve3yY
    rooms: 
  configs:
    netdata:
      data: |
        [global]
          memory mode = ram
          history = 3600
        [health]
          enabled = no