apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: mosquitto
stringData:
    passwords.conf: ENC[AES256_GCM,data:3zfz9fJQRHNS96PfPRTDlh8O,iv:FtjIXFoUDDNTybNitzCigY1bJq6Xp+aEP0mGsLIMnxQ=,tag:S54GoYfIdb7nJLdArUpuxg==,type:str]
sops:
    lastmodified: "2025-09-01T04:36:12Z"
    mac: ENC[AES256_GCM,data:9JvTfVUW7QE9oDfjHWMLCe57SmGw8oqKSAGgO9o2ie4YKtU8NzGgb0aKJbIMOk9NrEtHGqy1bKWs7Gynfgf4RgXAijqqxjvA0ngunvv8iAlQoboghvcxBc+cdZ7D8riZXSiWKifnK7I9IOdAm0lknuo/TVPPgVuJEY/dwRz+zsE=,iv:sxCtijJozvRcNQfRwZDPLj3wuhbYoZOlXo/DtJ0t3kk=,tag:X34aLPveeNTXRIQSUak+pQ==,type:str]
    pgp:
        - created_at: "2025-09-01T04:36:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/+JSWWJiHSyvcaXdrt4m+XmZKHOxWM6Ym+1tgG8p5w3uxa
            oC6lE+cVbrW2+Wmphyn1QDe7fM7ZQmSvkmPfiCCYE4OY1ZuCiOepFWDItTOLMuYn
            A0MvXswpi3iUMEBFS3Xa6xsBv3T/KFzcnX2Du0xK+DVlxR7KZQV7/7NENaP49qjE
            oOz+Dowo5HCw8JpfCCkt2u/0gbCkDucaIzuUxzVMLv0WQfLqDycn99dpXDIZNnZj
            OV4JJhGV0U0rdCbujxkHSZaaRGe6ragrdJDqr40xZls4kV5+2xRnJdz4Z1yRgXsA
            BXXEaLu/o2q90SysCHWs3E7HGvzNd0PJQz18k+Ryd/Iq+Va8yH7xnykG9qQakNT+
            dkKwkj202Gr0EDQyfNRrNIKRln1Uzw7CShLzKpDkz44rbAyy064RGc7K+MI65y3x
            0QKH7hMjnutDg+0748KXNJAA04caxY6SG3GeaeXtTHEOaqeHLaxAxXCTLVhK1ejo
            bpaldGJRRjcJKwKs+b+m8MG1vobIg2AAD3kC9mosfkVBtmmSz56q791MhcZmUD/9
            TIpgaWgprLY5fscWjOmz4WjrWOlkSygPiRnDYgtpQcBJlehPLoTAxhKHpW6LUgeW
            Q+kScQPNyvmdd0+9etlppH329wNGVUW51+7GdkWngGydxmNnFIVgb00kqPr2dyDU
            aAEJAhCPi/kArF6/GsmEoWWYO2FZWxfCYWCn5ygFFrS5GvuA7PDUPiwOO8PK/rlM
            8lHJgeVoyrTRBFCqGXtcYyYrA+7D1c/SLaD+sg/OsU164BsX+Ntjm0d++fvX1BIL
            +Pfo7rV3hziz
            =wPpK
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
