apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno-policies
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: '<4.0.0'
  interval: 10m
  # See https://github.com/kyverno/kyverno/blob/main/charts/kyverno-policies/values.yaml
  values:
    policyExclude:
      disallow-host-ports:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - ingress
