apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno-policies
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: '<4.0.0'
  interval: 10m
  # See https://github.com/kyverno/kyverno/blob/main/charts/kyverno-policies/values.yaml
  values:
    policyExclude:
      disallow-host-path:
        any:
        # Falco must bind to host filesystem paths for monitoring
        - resources:
            kinds:
            - DaemonSet
            - Pod
            namespaces:
            - falco
      disallow-host-ports:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - ingress
      disallow-privileged-containers:
        any:
        # Falco must run in privileged mode for eBPF
        - resources:
            kinds:
            - DaemonSet
            - Pod
            namespaces:
            - falco
