apiVersion: v1
kind: Secret
metadata:
    name: hermes-api-keys
    namespace: hermes
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:rwjh/RtbA4a/lMT5lPTY0eOYdb9UCl6DmgdqJx01enPocReBSEmGGS3bv4z2iLsdYqe84aaZj2A/JYw2AgjqL4Feb0WkWsw5M5/E7aWqUm3TuGI7vpkS+QXS1oM44WMSB7yCrdVooIy5FvwdL1R7drrvCErfDBT9lwTRGmjqy3lV+fsRIA7qI22PFIrng4p883XjlA==,iv:liwGo4//LU33TjUgqd7k/faIwGw+BXYuE0F4vUDVTgw=,tag:f2tHTlUe21DljCOiY6PPRA==,type:str]
    HERMES_DASHBOARD_OIDC_ISSUER: ENC[AES256_GCM,data:r7I1VmIVdiVNXkm1D0GZVvzbDNQWz64FOo/jgi2xqN6kZbvRH5Vc7kVvZr08UcYGDxlJ2Lh4V59tRThIEfbvE8UdwHk=,iv:YfboaGASZ0DzZvMfwiIJG/1X7u3YwgEmR3Xv84Wblfo=,tag:99XxK3vaiQnFyiTAM8MDug==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_ID: ENC[AES256_GCM,data:807Cy4Wn0qOOIC3M,iv:f2dy2WY0jufCaZdqyIbw71senuKVs+K6YWy7GmXlsO0=,tag:gA2mFQfbR3l1R4RccgPK2Q==,type:str]
    HERMES_DASHBOARD_OIDC_SCOPES: ENC[AES256_GCM,data:BOxkBJGbaHmcG3lduZJqVvYPdthFJmepUx4uNQ==,iv:ehkonkmvi+kUQEjDPQPxOk+3K937pSImPgGGStdWhaA=,tag:cAUcUUIlyqs3sHI/UcCa8Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T18:13:41Z"
    mac: ENC[AES256_GCM,data:AyqMMuPpWOeAj6jnXEboApLEPVBaiEumSEz3J28VyIpL7wcT+9lflxZCA0h7fttDs8nQtKQx98KFRZR0Rn1Su358bfzX5I4H0ez710pH4C6daUFwiJ7thTrHWfKgfxOW4sKPY84C96ThR3B6J9kCN589kULSHyBME7wRDSITfYY=,iv:YpmR1F9LnAv6XTor3dX8Ql5x9q5DHXd7vrUyGq/4V40=,tag:b85RrKMUTz9934CV+Gb7ZQ==,type:str]
    pgp:
        - created_at: "2026-07-18T18:13:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ/7BLCqTm8dIh5/uPHY7NIgP0XsztUav7fROF0U4cuSFCxd
            1RjCSPJwP6orle6IBz+rYK2g8PCxK3XK6oOwj8S4EUwS0n+sdoxoLcvDFco+GioR
            TP1obexG4OMvWqPu5CJzniTdMXgF9tJFE2n2wqT1sTPLZ97Ca0efnpTejtcKbRG/
            Q1x2pxDJvrfnC8SEmVBf9qC7q07Y3R8mwbSESubUZCA8bJMzdA423Pxjk2qNlvtI
            F7FniV4HhNhP1W4TG8kG/0Yp+lbdjbGqyEO1f18Y3B/K5IUzjdFy5mHa5VbKhyLy
            nhHuVMmOJo7SQBSUnw4DHUnusKWThhwqjosQXLAHK9wkoj302CYiaV+N7ac68RER
            hjY9DOfx1OHkWa2KY2B/pllvRZAO6GANzEbLISJ3OVMkZEwMAQK8+U8loltyGfCL
            1miwoLlKyd6Ou/6UsEyKb6FFqcEAjPflUtQANw3RiC0K7nJPXjIJDb8Kay8WlLD3
            7VfblVXYv+Hqrb9PARA3GZa5jJTphHSUR2NTt0ekOzUNfcoWQuujgtuwqzO/kqAE
            QodqIArz6l4R0La7C1r/FGUgcQZamIeuEW5FOD64qazrLQOG8fCwb7Cn+DB/a1UZ
            xecn7q3mFqDD73UZQHuCAeruLq3ywYfoGGgVI5ml6AMWKHNku9ucmsw1P/pbt2rU
            aAEJAhDT1vg5iVdBgpkQRjIGvf5lD/msIt7ouCp5GEfdVVHXaClhOCj1aHxQVzLU
            /69xr5NQhNXQUvUQbfZ1DY2ByPMgyXXeNRZsOwh37gZSrUrZRBkwXHsfduNDmOnp
            uhOIAw/Wlo6+
            =vOJ/
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
