apiVersion: v1
kind: Secret
metadata:
    name: hermes-api-keys
    namespace: hermes
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:tHyvw1UL81zFRZDvfZliscRSNOXqLgpFTfzVm1a2W7Z64SQDd8VMMPn9QbRD2Ay7nPy4n+RtPx5dOIJeBSmT8AVWTZ7rSi9KrMhuFFnjWsRvW7vYw//AbkGz0/hD964NBrrEJqgmU0Fy1KK29QiNAgATjZoUR+a6+IkxJTUFiAVim5RZdCXt4vBdpjh17bKI97VjJQ==,iv:Trm8qJguuUTB2Jb0TNniyx4g10ndvEbbiSdPednb5t8=,tag:URp24fVySHPimmNKjJTK8A==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:K+WOyLCzn+0=,iv:6q7KghodMzKFYf1FuJKLXnl4osE3QMwQpF/1qAGcdUg=,tag:aZTteVBlJjWNpA0LzW3njA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:E+EdhkamueK25XnUJqIuYC3MHya8i7TN0/QWhg==,iv:GWO6fuIZdzjs12TV6wSZxfFLMRDMoh+XPVq6LjV3B6Q=,tag:1yYtcMEyAFFNHlA1y5UAGw==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:eIYLNBpVLHxAqAt6zN+A9vPZVzohl2q0Jxf0tw==,iv:l+jdwsfHGkA5t2PBqJ5FDjfZcpmAste8TQuBMBMJ+9M=,tag:o3Y/CCLgIpgpEGKkNddDdA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T17:14:56Z"
    mac: ENC[AES256_GCM,data:L0qgR8KFxmyGQhNJva4qdqR7L0+sn0FNhPAsIUvl2mR8KrBeF8bqms1NyBFkrkHI+QNhSc/VGwV29qCPiJLzXQlgH3PzHQnw6Gk59yVOrwOZYg3T/g/aJCgDA9RDFVuW9konOVu7T1HWCG+7pUPeHTuPMxvAEO2aXPhLTpgXz/Y=,iv:YO3rLm8bvpSAKYX8LmQ1Oy/NpbWCK0TrbSprHtnfpDE=,tag:3Si5N+xfZhucE9CMK7j92g==,type:str]
    pgp:
        - created_at: "2026-07-18T17:14:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqARAAggMf8yl6s+qrzquuVO8m8zJlI21eF7/QX9SHcSYCwf9S
            z41rOh+YMiYKhbjjO/3m3la4eLxAqHJ2J0gLu2KAVWElDmSE9eCIssvJqoz9q+Ei
            2GyvCZTaLNiN7gz59VTd2/Yr2SLHrUiNfQb+RDBxNWApAfSvtJuTLqJ13tgRu2Oz
            8ZYtMJLLHzFBr16TgSmZD/Lx3b5ywPxYMJYubi5eQYrnqKZpOogVp7NmXUHrhOrM
            7Ldsg74zvnKfu55ffiS+Kt3Oc7WasweNgjqiwWp1NF4bJCy+BxH+K4n+YNskF4aT
            nE51+H7v6UdsXJRK/U32nwoXUeED1iggItsnQQwVWdI710T6KDVOibw/6GbFEWdM
            XmD9KfJAEPYgzPVdbZZI+/NgN+m0Qx7c896H6z+hixuy2/AMFntrYf6SB6MYVnkL
            rTZFYG2q8TxiQjghXxpRTQkET+duivq9E+Pb3OHbNKOBB/Do8rbFSRmLsCkZhkBZ
            qWqcLeGe2HHHrAzjjh5a0jlzDN6xSIy8wxgIzLjhUwihl5MxUshvAGxozFlwmwwj
            1fpSSM5nOF95jIxhhl6TeeGcguvTxZQT1Uqr9R1ZZ3qJfqAKPK8jJ8OPVIFR65Oi
            6Bl7fpi/EcPbO3h99RjDO1Jtv2P9TQZup1ccF5bKyuc89gMZgKCnfzaGuamVqVfU
            ZgEJAhCandsMdv9nhzGJ+pLvkkFYCstvOvsSo7SadoeKOe00r51Q48jNQ4A609xP
            6DFCkLnXyIJm9MSqgcillNRjoDPjHKWvBtgcQa6/UMkBOuUTQPFilWJBCJ5MjGPd
            6uSRGRnvig==
            =fqPU
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
