apiVersion: v1
kind: Secret
metadata:
    name: hermes-api-keys
    namespace: hermes
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:3HzbYAMezKlzZ/klYEEQEq+/HYaxqPx5LmABwbK0VGIarXKLCelFgt3gD8hR/m/glUJYSSVWvg/UfKLBtw51VC3cIIDbJhefyDxXHgFk9lFyJF9j9Twt9b1ocgBPlfnzgfg7G+5cZW+LiruE9ISa1W/M8XwyBtRX4Ozd4bigTXEeOW/I0tb3CTy99aqiWFTmhhqKxw==,iv:XS6/rJEVjfBURdrHVfLf02a0JN6zcWRYC2/TshgfAiE=,tag:ArcJVZiXiL3i+QTs0XOmHg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T16:52:33Z"
    mac: ENC[AES256_GCM,data:7u8xwp4YKSila7W7HWkjVngnAqVfRPGPgh0pep7kLXW3LsrflcnlxmyMcW28ztBroA2kleIu/N4rQMgzyfF4OrbEkAHoxTRC2yI+6ZoDnHRN3qhPZiRnhq3zLo/AWaLPAAb8FqQ93OczQUB3Q+eCZ8Qe5kc47PyzWtGjKGssXd4=,iv:hBS1miL33Xa82Ml7+B4U5J1rdH9WXSZZtXvD2Hl9zfk=,tag:RXQJSzclihqIcu7t91aSjA==,type:str]
    pgp:
        - created_at: "2026-07-18T16:52:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//QcEHp07UAqSHcjrm29nWLIQeRrDQeqAteOCgLvIrDKGQ
            Fq+gxS+bOmgszpHroQoQXnTvH2Ya847GILESniDqkWPsw4340hALAntqYhCsho5J
            x+/bnnFoCC/ilbHMU1p6hMbPohqVPGmyV2S09sb2ZYCEjzRK63tHZilEa+S2VXyM
            fM65LyMbkpnarj1Aqwfw9fe6gAi5kMhV3BSoxjL/39QYDxNMM+6tigr4u5HhjiVQ
            5O4vVyGVyP4Pr8UuIy2sJG1RRUzp6bpSvfeo9QDZtb4bISkMWmYB4wv7ctaBSQ32
            4H+HTNalkTIXG9mhDsyorfZRWMLtYHgUVkk7SBm9JYK3dQNBhMeoUokI5WZkA3de
            IKAjM8gAWaNDVI9hLo6hKhgDgwuQ/fPp5f61/wFkFC7MucY6egtOxkLb0fZxanby
            4/GHOwrk0K/io3ufQNy/yDpvsFYHKZh556bzrPhKWS66LDeYltmx09dfgqB5XqR/
            AmyN3prAkVsJP0JP00bK1MlIadZDKBK85QbWZ2zjZdXAj+vbklBjEc12CRwAzopf
            DObcEolUdSJtRegjHHeHXcjCVbHaSKofw+PxgF/r6euqnZMw9BlySM1gmpJcZ+9v
            Hpbvyc4V+EkOY5RmbAbnUROWeoI9/k2QrZicpaQW7taqRlLBfGiuw6R2j+KKB43U
            aAEJAhCTkSZNjR7JnQVrD95cgS10p6jK6Uc53A6NxBMWuv+2Ciq+YTgtrFqsaPvl
            L+wDsnv6rDz7krfnCx2aPqCH0Km067F9XjCr1D0/wzrwe85h0vdaGNA3meYjc7ea
            1saAWbIwNP4V
            =BvHr
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    version: 3.13.2
