apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes
  namespace: hermes
spec:
  serviceName: hermes
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
      - name: hermes
        image: nousresearch/hermes-agent:latest
        args: ["serve", "--host", "0.0.0.0"]
        imagePullPolicy: IfNotPresent
        env:
        - name: HERMES_DASHBOARD_PUBLIC_URL
          value: 'https://hermes.herron.dev'
        envFrom:
        - secretRef:
            name: hermes-api-keys
        ports:
        - name: gateway
          containerPort: 8642
          protocol: TCP
        - name: dashboard
          containerPort: 9119
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /opt/data
        resources:
          requests:
            cpu: 50m
            memory: 5Mi
          limits:
            cpu: "2"
            memory: 4Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: hermes
