apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
type: Opaque
data:
    adminToken: ENC[AES256_GCM,data:WhG9hbAxfxxXy7dU8xw2/W4Bogjkha8v+AufJpey0ea0oelPc6fctaRY/YtkexKNFpa55bHYyt0YvdyH2U4x4gmvksU40EpMgrjWjPbm0gFRawvgirK1Mw==,iv:psB+pb5R+448MKgwp+fK1nup3FUQETyfojGsii8AY40=,tag:9ku9ySTVlWl2HLkZNRtrpQ==,type:str]
    pushInstallationId: ENC[AES256_GCM,data:5CdfKWQI6z+hKbVq2WaYmvLWnzEEi8Ghe/os2eYyeiojX/2gdxOK7+xgynsIWneC1eDAAw==,iv:ghNSTx++yj9gk4QkM9cEBxQh6qtxUyfv08TJ7wskOZI=,tag:A9lGTyOAnCcbe0h6iPEiug==,type:str]
    pushInstallationKey: ENC[AES256_GCM,data:cb/kkBgLgq6WcD7jQjfjXS0THB0NK6lJL9pr4w==,iv:7aP1NQTJH3w+JorfLzMaRUZHEXhvPI+GNM4sSfyIOqc=,tag:qsGGJyvp8sP9aKoH6Nyx8Q==,type:str]
sops:
    lastmodified: "2025-07-18T04:00:38Z"
    mac: ENC[AES256_GCM,data:fPEwZ3zLwaOj/HX/mqSL9DJju9uLMl3xlB5gV+0hFGXzD/6w/w4x4wJK5kQzhJaXayhrDNMXwLtbjlrlhbM1Tw6lD6X5mkqs/gNK9fNWDZC+pothT3h4kzGknlfLt43OcRpQSmWT0pdNjawsODFKTkmgyc/oCQh9XlSoTol5grQ=,iv:dI4CfdxSv5Pu+DQUuOsUeHRvxMpl4/+T+6wGh/V2Qjc=,tag:gxDibI+jwi+6Lj8uYQATZg==,type:str]
    pgp:
        - created_at: "2025-07-18T04:00:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//cr6Kfmv+GZCnPRuot5HWU/K7Xp8KjsgSOR1Q+0+NwZwQ
            qHpD7qkiM9viynLOCM4+/qHkQaKTft7AKAn1ES4iOCC7RdH7RAHMy2dKnAFZqzaz
            vktU6ElduFcIJ/KwrTe45O6dNSN9+oGA4YK7UVu/HKfKXRcAHWm1OIY0zzkMVftw
            GCCNCchaILVe0I702qSAEgmzGUA7O9Eqt2Mybkn/jeGTJo/EKlWX00Rau8Rkzr4o
            wacGY34Boq5Qc3Ade+fLo7aV6pTLDWhPvqEGP561vfFhT64he7/RPia3j2VJHI+N
            AZzs5u46K+FkHwFqpEo4jXy3C5Q1cajRhoAhPrThNVyaNmeY7wd6nyTKhuhAUwkM
            nnII7L30w+cq17edrIno0r6zNmGoSNUwnKmafL3pjyYIg1IEcPM7k6F1HnjjdYwV
            qHbCQ9EhVaDCkKlCpLkVCqYfvR23KHbz8WG6OemhjKXfOe4tU4neXLxCwtyh/qLD
            RIqlAxBVdLzYoLwDaeWWHyfvG79x86Oz615QQPW+QOY0q7psYVsP504DYAfh0wx8
            2+ggR4M1+H0dkcFabi28Xz5R3TptbrGIOwMqkBi0Q42Q3r1fgGZBJ5gyzga96cQP
            zlW3K6N/ISFdk5XP6Vz59grgOmHnLCXJCfrRYyYD0tkr8r1aaMyp5Qx8tUXYsD7U
            aAEJAhCDiMUxJYFX1yz9ZJnyAz7xzWFuwIbN8iWncK1+CJxyi949LrQHXnvw4pwE
            GRVZlziwZOCaOqgM75SaqSx092Y15icttNqd+xpgAH9NoB1GWaypsyt2j2lFlmXK
            a6I1l8jt+Bp8
            =sXxd
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
