apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-api-keys
    namespace: zeroclaw
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:TkRa/dv/utuyTtUM95PLeD5TpaOwG5tY3JkoIMIel+Elt8pJCPB3BEnDgi9Ie3FV0u2tHVffmKltDlx5BL+MS1Do04m2tXqZ64YMQkjWpf435HAKfZ6DU/ztin/NsLmgCU89HHuj4c5Vq/G+,iv:uEvF038uoL/J6lrj3c4mUmraiITWLzU/Y1/hFt+61yM=,tag:0fwoFqO8fpBfzoR60OXTYQ==,type:str]
sops:
    lastmodified: "2026-04-12T03:57:11Z"
    mac: ENC[AES256_GCM,data:XSV9VayL2wWribBgF4QnyXFZg+0boLqzjUkUxzAGU5vmPChJAjRzA1MPYEC8r3tsXZzWUWG5rY0rn2PT2+iZKwF6n+rcmpcqdL0s/utVptuMpEot1v6CPqTHb34rX8+E9BXVRYB8/LRcvxCm91Jtzekyauwfgbiojzah3dUYZgA=,iv:8+G2pVfzKHTRsYgBzfWwzNyKnmZxa70SlV5oECK/UKQ=,tag:541TwWy8T0XBLractRHIHg==,type:str]
    pgp:
        - created_at: "2026-04-12T03:57:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//aDWYF/wMT+orr8/V0t6TosdrM9nGJNnVIiKKwzol9nMf
            o5eRTFvCxEB5LO0Pm5/98VxjPiXYMD/EjmW4+HmdGq2s64AwC3JF6/3bKZUsgO0F
            0PZ1T2yYil4MaYFTQXmhlfqqYT9E9+ZbupV0LeOgakPy/Du62+he9v1Co9xYJSE/
            DcfxeM9fJOldKuXmLzkCk22N7DV8Vx1ILtMrCbJlYtPbkBM8LjZ9ZeMYqjrvbwoJ
            kZwHXfwbZwS+JKUWuW2iZKdPO8Ou6DpAsnuFq8lgDvjNfHXnGq0tmn4qe+789+vy
            7YViwTWvrxhhlK4z1YbH5uIHS6pbZs4ZyOD4C5c42JmLjaQO00+oEkjhJhqSFhz0
            4JRnABtNPL17vom55vlOBaw3qGdcZVdzuw0XrcZooiJu2L+nLDsOtwWxulv/8ovV
            vpUmhd8hKwTAyn0GLw0vdAklV3hJDdAYWR2zOE8n5HrcY4yAaDEhaMQ/h272pyrP
            GIlgLPlIxdQZ0bYJlweRCNknn0MY+oQygXFRJ9jiJDMTQ1whQ+F+5CqbxAH6YYv6
            mQfahQuBzKyVJVhLFjvkLGU8Lk1Ht6p0bb04eTfk+XDJ1KYYVu1yHsX1IUH2OXsp
            bDLpo1Bmd3yBqBlsX4eZtFfo+T2NRFHX7eGZ7nnEX69qlM7IGXwq8zc3jnutPcvU
            ZgEJAhDG4q/UbUkHH1ByBqhEI9yvWs3fV7M8rGrhHcJ96Fs8+6yBeZ4bMKmY5rig
            7m57YATff2AQdcM6uqpnCAkPX5LOXZgyrOJat9NyBUI3zs4iyqE++rgbK7dfHk8V
            jL7Xmg3ZTg==
            =5Q0G
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
