apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-api-keys
    namespace: zeroclaw
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:mqIRGQBWXMj8rifKqn9Q3tk+aSopH1sCujL3V+936DgVBrenywpIoJ2EULIbNEuGKws6sHG5zjxGRCVJnfgHpshpbIkMiZ/Ygo9DNscOOf0Gs5PbSxjNPBsq/ZL0EP5MHguEI77zyGLVwYApGFWhb1RpOrYKlrJMp9TkxtIZo7AZvT4z2V7qA2hZFNYewNy+OZxCXg==,iv:9OjWU9zxpJKWXaHp7LsqEO+YZrEulNREl7r6573lgUY=,tag:Ym2vjJFKqc2aFitUrMs6aA==,type:str]
sops:
    lastmodified: "2026-04-12T04:47:06Z"
    mac: ENC[AES256_GCM,data:O/vClItNsxiJH03319TJOBDP+H3mt7fD2th5/9RNmlRzlffO8jVGed9MlgzOBHq0/pplcF5+eUmCeigS6gxVXq56ArOb+LNQGm6/6ARYnI+Qai/MVF2Gcei/5m/AiJsdxsNqPxabKz/73sTKYQaMa9Sj9hTdxKrbKapV7CHAjYE=,iv:D1hKHLHVhrwdMZXxVMv7zz4nKYBuQ12WN0phfVzCpGk=,tag:rIiKZT4vWsmhyei2Gtv8kA==,type:str]
    pgp:
        - created_at: "2026-04-12T04:47:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//RybAJ5xNzULPpJ5e46UyMzDzDd/JDd57rX2Nqx0Q7yGj
            /chLhSYOlMIpZZ8IxO/dQLa4qSpaTGOWPQez+LlkEAHPZd6d54HcU9daa8UT4G7H
            a5HVt/Lb5ihdn1shJZStxju4k77JGmRxdXel7Xhy0L8bLVt/201b2Tdut2npmLo7
            Yic0/wNwpsM2e9uvbR0NH326+Ou4EOVLoN5WGtv5v3vUGyStJn5xJ2zuF93aq/wQ
            IfQNopuOZ569Cn3XR8G+f/BGqDT4mMy0D8saoXWz5+q08XAeyRmrRyx7wIbx2vCO
            eZAdDniSS/r55ORGW5oBI8SBxfqFCz+cR2CwoYFDQFA0r+AKTjQGb+Y2ygfPF62+
            PEzrOlUQUqdk8Jz+29j654GbSRPLM3i3CiI3msz0tttYDOJXUFwfsun93J+7Y4x6
            E1jojQoeFVxlqt10padYyPf+i3Cd8lLf1Y/cEFBjX8I2pwWK28QKmouHpUvgDQZy
            7Lnx5FtOeeTR2vPF5qJlBgy8mnMsUv/2GWvqf9w1hoCxiYurU1TyeEqrVwxB6m1V
            YCrRRF9mZ0qKLMozKXss3zlJS9NHCCc9pwejZBqb4v7mg+lUKXZRu/wKTQTYf6XH
            EaUPQcDn0ZRUXCdNjmW4gD5vwD0xEawa+M6XTiiU7MNQybT+ZvaMScdFdAd4SM3U
            ZgEJAhA9epZ+Azxq2hEj6h5fIXaI7vlr5MTxP2+lcavdOilLwviuQ6mf5FXp3+4S
            o5Nmuf4pJfrdo+/xX1VhkOJ5zlL1cgsZehcinYigtJZmvH1uaYF8CqaV0o9I0ZwI
            ylC4O6IY7w==
            =Xciz
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
