apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-api-keys
    namespace: zeroclaw
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Xn8wwC0NHKst/pkzEAJXzQBYcDUX2GWcCB6FLI8H0vEVszTjgO/39vK7pyLjt1v6mO+3dkQNYBrz1+WpjA2PAjWTb4vRH+zn0ei51BT0DtcbZU7Pm1UvtjlTEDxO8b8+bLYCxc/zxwue1EQdUn+2IVGFf3ZTq4P5rOrqQElDxGmLA07pHw/Q3wTJTIEbQ60EgWvhpA==,iv:5QCuQhPekzB3PK+ng6FKGXixlhRx8s9Acp8BbC/qg7s=,tag:9FuvxirIKJJDRoLn1/y8sA==,type:str]
sops:
    lastmodified: "2026-04-12T04:56:56Z"
    mac: ENC[AES256_GCM,data:UOOByXDEqm8Cq2iKEduN5OXvng8k60yqzvwjK7f0koA7l1LtiXm5eQhJ0ssRv9xunX5ZfO791ykMEpE/uWJSPlN3IQ+E6JZo9AO9UrcTC1YLdevpLmTKN6JY5B1Vt4Tg0exXZpb7FbNJ9ykxf6Hq8AW7vK2rknWlrpqw4Gel9Co=,iv:P2lFj8lAGhsMuAIKCLmJqETLdk3poHWffsaRzvZN5hE=,tag:qzQ6NWEJwZDlVUMlruI4IQ==,type:str]
    pgp:
        - created_at: "2026-04-12T04:56:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7zTuO7KTdvqAQ//ZGTHhQN4CHCceKfX/ZJK8kNvCkK1vBytWU5i7jGC8iZ5
            2UpLof8nAGnFuzuB+w2IbD+0ZnRBPc4/7BCxIEu2zouW2hC5Fub8+wNfnrw4BE5O
            zdBrAdnnD/BTkLepJEkMUxh3xIm4ft3f05oBLxVLPTdgxFO5rNJfrqb8bU/OyTIy
            iPPDHOnFnVX5LPkOA+0HjPKKamrwCAvLnSoI4WnbrcDdGUXxfg8ctcEnZY9knAgv
            9j5HGhNCrNLJrRaEmaGDtvQ8pahsquVIbbm/+r63hjUuXEbcpeOyo7z9NMiwBK9L
            aOanoK0DOgyHmu60Tf99xD5iqyKJDc4i9cJhtk6IwaPS17aiJ8RFt/wE/I7wdwn2
            HA4fz3FbcK7YrV3kFl9/SP06yzM8PqJxNL5GKnFuwNr1DrhP4qVktqMYTvurGq79
            Tf7DhtOVnkLrpD3uiNKVYz3MB0m06RqenJCVpsINxtZKOkn7TAcxnbZtiy5WC7Cf
            Gd/ft1PYUSR2yqS4qeiu1JLi1a9WndyKvTdBCUEQ4O3sOmN+9iNkGsLvWCnYEMdk
            /Ye9pU2al60F4lLX1Bb0j+XzoAEEIrInASWVF3NorqBMocF7/G5EnZ26MePwwd1A
            UjOEHx61L48N6JQm4kQVQsYhe+iEdk5EzCo+/zgUARkvKnXXfRHudNiv/M33fW/U
            ZgEJAhCmruPZ+BdfJIXEc/1Dp8LQvP2xxSRc4Q4pSkmeVIiePYFTzVlcBlExc+Jc
            KD1qJYnUXN25Ggi/oCiNmvDol3WHl/NI1GoXn0lRJl2JQR5x5zUG3eaafyHITxC3
            wnOu2cuNSQ==
            =kqsz
            -----END PGP MESSAGE-----
          fp: CF6D06AA52C1DA3E76585A354BBD1060CD804318
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
